Jenkinsfile, docker/dockerfile-build-ubuntu-16.04, docker/dockerfile-hip-ubuntu-16.04
For continuous integration enablement
=> Initial Jenkinsfile and dockerfiles for CI

src/hip_event.cpp
=> Don't crash for hipEventDestroy(NULL)

tests/src/deviceLib/hipTestDeviceSymbol.cpp
Enabled directed tests for testing memcpytosymbol family functions test.
=> Enable memcpytosymbol family functions test

bin/hipcc, samples/0_Intro/square/square.hipref.cpp
1. Changed hipcc to use rocm_agent_enumerator
2. Changed square sample test to use device variable
=> fixed device selection during compilation to use rocm_agent_enumerator

src/hip_memory.cpp
=> fix hipMemcpy2DAsync

INSTALL.md
=> [doc] Add details of HIP build time dependencies to INSTALL.md

tests/src/runtimeApi/memory/p2p_copy_coherency.cpp
Disabling this test till it gets fixed.
=> Disable failing test p2p_copy_coherency

tests/src/runtimeApi/device/hipDeviceGetByPCIBusId.cpp, tests/src/runtimeApi/device/hipDeviceGetPCIBusId.cpp
Added tests for hipDeviceGetPCIBusId and hipDeviceGetByPCIBusId.
=> PCI Bus ID related dtests

src/hip_device.cpp
Device count range  check on input device id function argument.
=> Device count range check on input device id function argument

src/hip_memory.cpp
Null check on input pointer arguments
=> Null check on input pointer arguments

src/hip_memory.cpp
Fixed hipMallocArray for 1D cases
=> Fixed hipMallocArray for 1D cases

bin/hipify-perl, include/hip/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime_api.h
Made changes to NVCC headers such that they are more C compiler friendly
Add missing CUDA tags to hipify-perl
=> Modify hip headers such that they are more compatible with strict C compiler

Jenkinsfile
@ROCm-Developer-Tools/hipsters 
This PR enables 2 new features into HIP CI:
1.  If kicking off a manual build, Jenkins will prompt with a checkbox 'push_image_to_docker_hub', which if selected will push a docker image of a successfull build of the combined HCC&HIP build to the rocm org on docker hub.
2.  Logic is added to enable integration testing of an upstream build of HCC.  A separate pull request for HCC will be made to enable that functionality.  
Integration testing is defined as building HIP and running directed tests of HIP, as part of an upstream build of HCC.  This upstream build of HCC will typically be a PR into HCC, and the integration test run determines if the HCC PR will break the master branch of HIP.  The HCC PR will flag a red X if the HIP tests don't successfully pass …
=> HCC integration testing

docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/Cuda2Hip.cpp
=> [HIPIFY] Fix typo in doc

src/hip_texture.cpp
This resolves the mismatch seen hip texture fetch.
=> Fixed hipTexture fetch issue

Jenkinsfile
To the failure of deleting images.  This is happening as I add more projects into jenkins, using the HiP image as a base image.  Docker will refuse to delete a HiP image when another project is using it in the FROM: line in a dockerfile.
I will address deleting of docker images that fail in another way.
=> Make docker_clean_images more resilient

include/hip/nvcc_detail/hip_runtime_api.h
May require further changes as I push texture samples.
=> Fix texture support on HIP/NVCC path

hipify-clang/CMakeLists.txt, hipify-clang/src/Cuda2Hip.cpp
As requested, filing prefixes of #213 as separate PRs.
=> [HIPIFY] Migrate hipify-clang to a newer version of clang

hipify-clang/CMakeLists.txt, tests/hipify-clang/axpy.cu, tests/hipify-clang/concurentKernels.cu, tests/hipify-clang/cudaRegister.cu, tests/hipify-clang/lit.cfg, tests/hipify-clang/lit.site.cfg.in, tests/hipify-clang/run_test.sh, tests/hipify-clang/square.cu
This:
- Fixes the existing, broken lit test.
- Adds a number of new, more interesting lit tests.
- Uses LLVM FileCheck for validating lit tests, so you can have far more
readable test code.
- Uses a fancy little trick to get pretty, coloured errors out of lit/
FileCheck when you get a test failure:
Note that a couple of the tests here fail due to bugs in hipify that are
fixed on my fork. The hip tests have been failing for a long time anyway
due to the `hipLaunchKernelGGL` thing, but if you really want you can
XFAIL some of them when merging this. Or you can just leave it until the
fixes make their way through review :D
=> [HIPIFY] Make the automated tests more useful

Jenkinsfile
=> Update container to newer cuda driver and sdk 9.0

hipify-clang/src/Cuda2Hip.cpp
=> [HIPIFY] Do not process __fetch_builtin_* in cudaCall()

CMakeLists.txt, hipify-clang/CMakeLists.txt, hipify-clang/README.md
A few different things, broadly getting us to the position we agreed we
"eventually" wanted over in #230. Oooor you could just ignore the LLVM
changes and take the other useful stuff that's here :wink:
See commit messages for details, as usual.
=> [HIPIFY] Make the cmake build system more friendly

tests/src/runtimeApi/device/hipDeviceComputeCapability.cpp, tests/src/runtimeApi/device/hipDeviceGetName.cpp, tests/src/runtimeApi/device/hipDeviceSynchronize.cpp, tests/src/runtimeApi/device/hipDeviceTotalMem.cpp, tests/src/runtimeApi/device/hipGetDevice.cpp, tests/src/runtimeApi/device/hipRuntimeGetVersion.cpp, tests/src/runtimeApi/device/hipSetCachceConfig.cpp, tests/src/runtimeApi/device/hipSetDevice.cpp, tests/src/runtimeApi/device/hipSetDeviceFlags.cpp
Added new tests for device runtime APIs. 
hipDeviceComputeCapability
hipDeviceGetName
hipDeviceSynchronize
hipDeviceTotalMem
hipGetDevice
hipRuntimeGetVersion
hipSetCachceConfig
hipSetDevice
hipSetDeviceFlags
=> [newTests]Adding tests for device APIs

src/hip_module.cpp
This introduces correct support for agent global variables, and implements hipModuleGetGlobal as an actual equivalent for cuModuleGetGlobal.
=> Support for agent globals

tests/src/kernel/inline_asm_vadd.cpp
Enabled the test on nvcc. Please review.
=> [nvccTests]Enabled inline_asm_vadd on nvcc

bin/hipcc, tests/src/deviceLib/hipTestHalf.cpp
Fixed hipTestHalf test example too.
=> Fixed half2 issue on gfx900

src/device_functions.cpp
=> Fix float2int rounding functions

RELEASE.md, docs/markdown/hip_porting_driver_api.md, docs/markdown/hip_porting_guide.md, include/hip/hcc_detail/driver_types.h, include/hip/hcc_detail/hip_runtime_api.h, include/hip/hcc_detail/texture_functions.h, include/hip/hcc_detail/texture_types.h, include/hip/hip_runtime_api.h, samples/2_Cookbook/11_texture_driver/Makefile, samples/2_Cookbook/11_texture_driver/tex2dKernel.cpp, samples/2_Cookbook/11_texture_driver/texture2dDrv.cpp, src/hip_hcc_internal.h, src/hip_memory.cpp, src/hip_module.cpp, src/hip_texture.cpp, tests/src/texture/hipTextureRef2D.cpp
First level support for texture driver APIs. Requires incremental support of further APIs.
=> Texture driver APIs support

samples/2_Cookbook/12_cmake_hip_add_executable/CMakeLists.txt, samples/2_Cookbook/12_cmake_hip_add_executable/MatrixTranspose.cpp, samples/2_Cookbook/12_cmake_hip_add_executable/Readme.md
=> [samples] Adds a sample that shows using HIP with cmake

include/hip/nvcc_detail/hip_runtime_api.h, tests/src/runtimeApi/device/hipGetDeviceAttribute.cpp
Fix hipGetDeviceAttribute dtest for HIP/NVCC
=> Fix hipGetDeviceAttribute dtest for HIP/NVCC

tests/src/p2p/hipPeerToPeer_simple.cpp, tests/src/test_common.h
- Moved test inside p2p dir
- Updated HIPCHECK to ignore hipErrorPeerAccessAlreadyEnabled
- Added check for mGPUs
=> Fixed hipPeerToPeer_simple test

bin/hipcc
Fixed gpu deprecated targets warning. please review and merge.
=> [nvccWarnings] Fix gpu deprecated targets warnings

CMakeLists.txt, src/hip_fp16.cpp, src/macro_based_grid_launch.inl
- Added static code analysis using cppcheck
- Fixed couple of warnings reported by cppcheck
=> [cmake] Added target static_check for static code analysis

include/hip/hcc_detail/driver_types.h, include/hip/hcc_detail/hip_runtime_api.h, src/hip_memory.cpp, src/hip_texture.cpp
- 3D texture driver APIs
- hipMalloc3D
- hipMemcpy3D for destination other than array
=> Added support for 3D texture driver apis

Jenkinsfile, docker/dockerfile-build-ubuntu-16.04
Getting jenkins back to green builds
=> Fix hcc ctu build

docs/markdown/CURAND_API_supported_by_HIP.md, hipify-clang/src/CUDA2HipMap.cpp, tests/hipify-clang/cuRAND/poisson_api_example.cu
+ add missing types
+ doc update
=> [HIPIFY][tests] add poisson-api-example test

include/hip/hcc_detail/program_state.hpp, src/hip_memory.cpp, src/hip_module.cpp, src/program_state.cpp
-Fixed host allocated globals address lookup for host usage
-Fixed texture driver APIs failure
=> Fixed host allocated globals address lookup for host usage

include/hip/hcc_detail/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime_api.h, src/hip_memory.cpp
- hipMemcpyFromArray
- hipMemcpyAtoH
- hipMemcpyHtoA
=> Added support for hipMemcpy Array functions-

CMakeLists.txt, include/hip/hcc_detail/hip_runtime.h, include/hip/hcc_detail/hip_runtime_api.h, include/hip/hcc_detail/hip_surface_types.h, include/hip/hcc_detail/surface_functions.h, include/hip/nvcc_detail/hip_runtime_api.h, src/hip_surface.cpp, src/hip_surface.h, tests/src/surface/hipSurfaceObj2D.cpp
Added surface object APIs support
=> Added surface object support

src/hip_texture.cpp
Fix offset issue in texture driver APIs
=> Fix offset issue in texture driver APIs 

samples/2_Cookbook/11_texture_driver/tex2dKernel.cpp, samples/2_Cookbook/11_texture_driver/texture2dDrv.cpp
Fixed function not found issue in texture driver api sample
=> Fixed function not found issue in texture driver api sample

include/hip/hcc_detail/driver_types.h
Fix TRFS flags for texture driver api
=> Fix texture driver api TRFS flags

src/hip_memory.cpp
=> hipMemset refactoring

src/hip_module.cpp
-Fixed missing ihipLogStatus in hipModuleLoad()
-Fixed some ihipXXX functions
=> hip_module code cleanup

include/hip/hcc_detail/texture_functions.h
Resolve tex1D float to int conversion issue
=> Resolve tex1D float to int conversion issue

docs/markdown/hip_deprecated_api_list.md, docs/markdown/hip_porting_driver_api.md, include/hip/hcc_detail/hip_runtime_api.h
Mark hipCtx APIs as deprecated
=> Mark hipCtx APIs as deprecated

include/hip/hcc_detail/driver_types.h, include/hip/hcc_detail/hip_runtime_api.h, include/hip/hcc_detail/texture_types.h, include/hip/hip_runtime_api.h
Fix gcc build issues for host code.
=> Fix gcc build issues for host code

include/hip/hcc_detail/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime_api.h, src/hip_memory.cpp
=> Fix texture 3D for HIP/NVCC

hipify-clang/src/CUDA2HipMap.cpp, hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, hipify-clang/src/Statistics.cpp, hipify-clang/src/Statistics.h, tests/hipify-clang/lit.cfg, tests/hipify-clang/lit.site.cfg.in
- based on https://github.com/ROCmSoftwarePlatform/hipDNN.
- lit testing was supplemented with CUDA_DNN_ROOT_DIR for cuDNN testing.
- single cuDNN test was added.
=> [HIPIFY] Initial cuDNN support

hipify-clang/README.md
+ supported CUDA version to LLVM version correspondence table is added.
+ Test section is rewritten.
+ Windows support is added.
=> [HIPIFY][doc] Readme.md update

hipify-clang/src/CUDA2HipMap.cpp
- not finished yet.
- based on https://github.com/ROCmSoftwarePlatform/hipDNN.
- testing on https://github.com/baidu-research/DeepBench.
=> [HIPIFY][DNN] support of cuDNN 7.1.3 - continuation

samples/1_Utils/hipCommander/Makefile
Fixed hipCommander Makefile for nullKernel source file name.
=> Fix hipCommander Makefile

src/hip_memory.cpp
Fixed hipMemcpy2D to handle 1D memcpy case
=> Fixed hipMemcpy2D to handle 1D memcpy case

src/hip_memory.cpp
I am still working on single kernel launch optimization.
=> Fix for memcpy2DAsync for pinned host memory case

src/hip_memory.cpp
Fixes both hipMemcpy2D and hipMemcpy2DAsync for pinned memory case.
=> Fixed memcpy2D for pinned memory case using 2D kernel

src/hip_memory.cpp
=> Optimize memcpy2D kernel use

src/math_functions.cpp
Adding overloads for abs that are found in cuda's math_functions.
=> Adding double/long int signatures for abs

tests/src/texture/hipTextureObj2D.cpp, tests/src/texture/hipTextureRef2D.cpp
Fix tex2D tests for result value
=> Fix tex2D tests for result value

include/hip/nvcc_detail/hip_runtime_api.h
Fix hipBindTexture on NVCC path
=> Fix hipBindTexture on NVCC path

tests/src/surface/hipSurfaceObj2D.cpp
Fix surface 2d object test for testResult
=> Fix surface 2d object test for testResult

include/hip/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime_api.h, src/hip_device.cpp, src/hip_hcc.cpp, tests/src/runtimeApi/device/hipGetDeviceAttribute.cpp
Add integrated device property
=> Add integrated device property

src/hip_memory.cpp
Fix depth value for 3D allocations
=> Fix depth value for 3D allocations

src/hip_memory.cpp
=> Fix hipMemcpy3D for fast path

include/hip/nvcc_detail/hip_runtime_api.h
Map hipArray alloc flags on NVCC
=> Map hipArray alloc flags on NVCC

include/hip/nvcc_detail/hip_runtime_api.h
Add getTextureResourceDescriptor on NVCC
=> Add getTextureResourceDescriptor on NVCC

src/hip_memory.cpp
Fix stream resolution in memcpy2dasync
=> Fix stream resolution in memcpy2dasync

include/hip/hcc_detail/math_functions.h, include/hip/hcc_detail/math_fwd.h
=> Removes use of unimplemented OCML functionality.

docs/markdown/hip_deprecated_api_list.md
Edited hip deprecated apis doc
=> Edit hip deprecated apis doc

include/hip/nvcc_detail/hip_runtime_api.h
Added tex2dlayered mapping for HIP/NVCC
=> Added tex2dlayered mapping for HIP/NVCC

include/hip/nvcc_detail/hip_runtime_api.h
Corrected enum type for TextureReadMode
=> Corrected enum type for TextureReadMode 

include/hip/hcc_detail/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime_api.h
Added another overloaded definition of hipBindTextureToArray for direct porting.
=> Added another overloaded definition of hipBindTextureToArray for direct porting.

include/hip/nvcc_detail/hip_runtime_api.h
Added hipGetTextureAlignmentOffset and hipGetChanDesc on NVCC path, this is being used in #514
=> Add hipGetTextureAlignmentOffset and hipGetChanDesc on NVCC path

src/code_object_bundle.cpp
This patch fix the following build failure with latest hcc:
/home/yaxunl/git/hip-lib/hip/src/code_object_bundle.cpp: In function ‘std::string isa_name(std::string)’:
/home/yaxunl/git/hip-lib/hip/src/code_object_bundle.cpp:46:31: error: no matching function for call to ‘std::basic_string<char>::push_back(const std::basic_string<char>&)’
triple.push_back(x);
^
/home/yaxunl/git/hip-lib/hip/src/code_object_bundle.cpp:46:31: note: candidate is:
In file included from /usr/include/c++/4.9/string:52:0,
from /usr/include/c++/4.9/random:40,
from /usr/include/c++/4.9/bits/stl_algo.h:66,
from /usr/include/c++/4.9/algorithm:62,
from /home/yaxunl/git/hip-lib/hip/src/../include/hip/hcc_detail/code_object_bundle.hpp:27,
from /home/yaxunl/git/hip-lib/hip/src/code_object_bundle.cpp:1: …
=> Fix build failure in code_object_bundle.cpp

docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HipMap.cpp, include/hip/hip_runtime_api.h
+ update docs
+ fix typo in hip_runtime_api.h
=> [HIPIFY] Support of cudaComputeMode / CUcomputemode

bin/hipcc, include/hip/hcc_detail/hip_runtime.h, include/hip/hcc_detail/math_functions.h, tests/src/deviceLib/hipStdComplex.cpp
This is for supporting TensorFlow
=> Support std::complex for hip-clang

tests/src/runtimeApi/memory/hipMemset3D.cpp
=> Cleaned up hipMemset3D test

tests/src/kernel/hipLaunchParmFunctor.cpp
Please review the unit tests written for funtor
=> Adding functor unit tests 

tests/src/kernel/hipLaunchParm.cpp
Adding more struct scenarions and a ResultValidation()
=> Adding a few more struct scenarions and a ResultValidation()

docs/markdown/CUDNN_API_supported_by_HIP.md, hipify-clang/src/CUDA2HipMap.cpp, tests/hipify-clang/cuDNN/cudnn_softmax.cu
+ add doc for CUDDN API supported by HIP
+ cuDNN softMax test
=> [HIPIFY][DNN] cuDNN support revise

docs/markdown/hip_porting_driver_api.md
This is for documenting the change in hip-clang: https://reviews.llvm.org/D49083
=> Document hip-clang fatbinary format and initialization function

src/hip_texture.cpp
=> Set offset in hipGetTextureAlignmentOffset

docs/markdown/CUBLAS_API_supported_by_HIP.md, hipify-clang/src/CUDA2HipMap.cpp, tests/hipify-clang/cuBLAS/cublas_0_based_indexing.cu, tests/hipify-clang/cuBLAS/cublas_1_based_indexing.cu, tests/hipify-clang/cuBLAS/cublas_sgemm_matrix_multiplication.cu
+ doc for CUBLAS API supported by HIP
+ 3 tests: 0 & 1 based indexing, sgemm matmul
=> [HIPIFY][BLAS] cuBLAS support revise

docs/markdown/CUFFT_API_supported_by_HIP.md, hipify-clang/README.md, hipify-clang/src/CUDA2HipMap.cpp, hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, hipify-clang/src/Statistics.cpp, hipify-clang/src/Statistics.h, tests/hipify-clang/cuFFT/simple_cufft.cu, tests/hipify-clang/headers_test_09.cu
+ Add API_FFT support (data types and functions)
+ Add CUFFT_API_supported_by_HIP.md
+ Add simple_cufft.cu test
=> [HIPIFY][FFT] Add cuFFT support

docs/markdown/cuComplex_API_supported_by_HIP.md, hipify-clang/README.md, hipify-clang/src/CUDA2HipMap.cpp, hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, hipify-clang/src/Statistics.cpp, hipify-clang/src/Statistics.h, tests/hipify-clang/cuComplex/cuComplex_Julia.cu
+ Add API_COMPLEX support (data types and functions)
+ Add cuComplex_API_supported_by_HIP.md
+ Add cuComplex_Julia.cu test
=> [HIPIFY][Complex] Add cuComplex support

bin/hipcc
=> [hipcc] Remove libhsakmt from linker flags

Jenkinsfile, docker/dockerfile-build-ubuntu-16.04
- Removed hcc integration logic for now
- No longer publish docker images to artifactory or docker hub
- Switch to new docker images and new test node
=> [ci] New CI flow

tests/src/compiler/hipClassKernel.cpp, tests/src/compiler/hipClassKernel.h
Adding tests to validate class size >8 bytes along with packing and other tests. This also includes the empty   class tests from other PR as well.
=> Adding class size>8bytes tests

include/hip/hcc_detail/device_functions.h, tests/src/deviceLib/hipTestClock.cpp
These functions are defined in CUDA SDK and used by Eigen.
=> Add clock() and clock64()

include/hip/hcc_detail/host_defines.h
Related to SWDEV-163084. @mangupta Is this what we want?
=> __forceinline__ needs inline and always_inline

tests/src/compiler/hipClassKernel.cpp, tests/src/compiler/hipClassKernel.h
Adding test for friend class/function. Looks like there is a known issue, hence disabling for the time being,
=> [HIP-Clang]Add friend class/function test

src/hip_texture.cpp
=> Fixed image width for linear resource type texture

docs/markdown/hip_porting_guide.md
A few minor edits: 
* A few typos
* fixed a few links
* adding a section on equivalent libraries
=> Updates to HIP porting guide 

hipify-clang/src/Statistics.cpp, hipify-clang/src/Statistics.h, hipify-clang/src/StringUtils.cpp, hipify-clang/src/StringUtils.h
+ Fix typo with missing comma in counterNames array
+ Change std::string argument to const std::string& argument in all functions
=> [HIPIFY][fix] Fix typo and functions' string arguments

hipify-clang/README.md
+ Split Linux and Windows sections
+ Rewrite Testing section
=> [HIPIFY][doc] Update README.md

src/hip_memory.cpp, src/hip_module.cpp
=> Fixed hipMemcpyToSymbol doesn't work on GPU other than device 0

docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Driver_API_functions.cpp, hipify-clang/src/CUDA2HIP_Driver_API_types.cpp, hipify-clang/src/CUDA2HIP_Runtime_API_functions.cpp
+ for all CUDA versions
+ add missing types
+ fix typos
+ sync with HIP
+ update CUDA_Driver_API_functions_supported_by_HIP.md
+ formatting, annotating
=> [HIPIFY] CUDA Driver API functions total revise (up to CUDA 10.0)

docs/markdown/CUSPARSE_API_supported_by_HIP.md, hipify-clang/README.md, hipify-clang/src/CUDA2HIP_SPARSE_API_types.cpp
+ Add all cuSPARSE types
+ Update CUSPARSE_API_supported_by_HIP.md
=> [HIPIFY][SPARSE] Data types support

src/hip_memory.cpp
Fixes SWDEV-167207 with https://github.com/RadeonOpenCompute/hcc/pull/930
=> Fix hipHostRegister

docs/markdown/CUSPARSE_API_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_SPARSE_API_functions.cpp, hipify-clang/src/CUDA2HIP_SPARSE_API_types.cpp, tests/hipify-clang/cuSPARSE/cuSPARSE_01.cu, tests/hipify-clang/cuSPARSE/cuSPARSE_02.cu
=> [HIPIFY][SPARSE] Helper and Level 1,2 functions

docs/markdown/CUSPARSE_API_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_SPARSE_API_functions.cpp, tests/hipify-clang/cuSPARSE/cuSPARSE_01.cu, tests/hipify-clang/cuSPARSE/cuSPARSE_02.cu, tests/hipify-clang/cuSPARSE/cuSPARSE_03.cu
=> [HIPIFY][SPARSE] Level 3 functions

docs/markdown/CUSPARSE_API_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_SPARSE_API_functions.cpp, tests/hipify-clang/cuSPARSE/cuSPARSE_04.cu
=> [HIPIFY][SPARSE] Extra functions

docs/markdown/CUSPARSE_API_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_SPARSE_API_functions.cpp, tests/hipify-clang/cuSPARSE/cuSPARSE_05.cu
=> [HIPIFY][SPARSE] Preconditioners Reference: Incomplete Cholesky Factorization: level 0

docs/markdown/CUSPARSE_API_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_SPARSE_API_functions.cpp, tests/hipify-clang/cuSPARSE/cuSPARSE_06.cu
=> [HIPIFY][SPARSE] Preconditioners Reference: Incomplete LU Factorization: level 0

docs/markdown/CUSPARSE_API_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_SPARSE_API_functions.cpp, tests/hipify-clang/cuSPARSE/cuSPARSE_09.cu, tests/hipify-clang/cuSPARSE/cuSPARSE_10.cu, tests/hipify-clang/cuSPARSE/cuSPARSE_11.cu, tests/hipify-clang/lit.cfg
=> [HIPIFY][SPARSE] Add 3 more CUDA 10.0 tests

src/hip_memory.cpp
=> Fixed hipPointerGetAttributes for hostmalloced ptr

hipify-clang/src/Statistics.cpp, hipify-clang/src/Statistics.h, hipify-clang/src/main.cpp
[issue #801] Errors in hipification statistics
=> [HIPIFY][fix] Fix for #801

hipify-clang/src/Statistics.cpp, hipify-clang/src/Statistics.h
+ Signs of the converted file are extended
+ Total converted lines and total elapsed time are fixed
+ Zero rates are excluded from statistics
=> [HIPIFY][fix] Fix for the rest of found bugs in Statistics

hipify-clang/src/main.cpp
+ Do temp file copying instead of renaming
+ Replace all file routine functions with LLVM's
+ Do not output hipified file in case of errors
=> [HIPIFY][fix][#824] Fix the bug with -inplace option

hipify-clang/src/LLVMCompat.cpp, hipify-clang/src/LLVMCompat.h, hipify-clang/src/main.cpp
+ sys::fs::make_absolute fro LLVM < 5.0
+ sys::fs::real_path for LLVM >= 5.0
=> [HIPIFY] LLVM compatibility

hipify-clang/src/main.cpp
'include/cuda_wrappers' should go first.
=> [HIPIFY][fix] Change system includes order

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/program_state.hpp, src/program_state.cpp
=> Fix issues with prior iteration of 731

hipify-clang/README.md, tests/hipify-clang/lit.cfg, tests/hipify-clang/lit.site.cfg.in
=> [HIPIFY][tests] CUDA 7.0 is also supported

docs/markdown/hip_programming_guide.md
This is for a review for clang https://reviews.llvm.org/D57527
=> Update hip_programming_guide.md about long double type

samples/2_Cookbook/8_peer2peer/peer2peer.cpp
Fixes error codes in P2P sample test
=> Fix error codes in P2P sample test

hipify-clang/src/CUDA2HIP.cpp, hipify-clang/src/HipifyAction.cpp, hipify-clang/src/Statistics.cpp, hipify-clang/src/Statistics.h
+ Add utility functions isToRoc, isHipUnsupported, isRocUnsupported, isUnsupported
=> [HIPIFY][BLAS] Restrict hipification to 'ROC' to BLAS library only

packaging/hip_base.prerm, packaging/hip_hcc.prerm
- Add failsafe in case of non existant files or directories.
=> [packaging] Add checkpoints in prerm scripts

include/hip/hcc_detail/texture_functions.h
This should fix the texture issue in hip-clang.
=> Fix texture using constant addrspace 4

include/hip/hcc_detail/hip_atomic.h
=> Fix signature for unsigned long long variant of atomicExch

docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, docs/markdown/CUDNN_API_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_DNN_API_functions.cpp, hipify-clang/src/CUDA2HIP_DNN_API_types.cpp, tests/hipify-clang/unit_tests/libraries/cuDNN/cudnn_convolution_forward.cu
+ CUDNN_API_supported_by_HIP.md update
+ CUDA_Runtime_API_functions_supported_by_HIP.md update
+ libraryPropertyType_t is moved to Runtime
+ test update
=> [HIPIFY][DNN] Revise and sync with CUDNN 10 and hipDNN

include/hip/hcc_detail/host_defines.h
=> Fix forceinline for non HCC compilation

samples/1_Utils/hipBusBandwidth/hipBusBandwidth.cpp
=> Fix hipBusBW sample for P2P bidirectional test

tests/src/runtimeApi/memory/hipMemset.cpp
Added result check and hipMemsetAsync test
=> [dtest] Update hipMemset test

tests/src/dynamicLoading/complex_loading_behavior.cpp
Existing HIT syntax doesn't seem to support the expected build and run steps
for this test.
Please help review how to amend the test case so it can be properly added to HIP `make build_tests`.
=> Add one test case for complex dynamic loading behavior

include/hip/hip_hcc.h, samples/0_Intro/module_api/launchKernelHcc.cpp, src/hip_module.cpp, src/hip_stream.cpp
Requires some further testing.
=> Add extension for kernel concurrency on same stream

include/hip/hcc_detail/hip_runtime_api.h
This is urgent PR to unblock HIP/VDI CI.
=> Fix HIP/VDI build failure due to dlopen change

samples/0_Intro/module_api_global/runKernel.cpp, samples/0_Intro/module_api_global/vcpy_kernel.cpp
Modified module_api_global sample to include hipModuleGetGlobal.
=> Test hipModuleGetGlobal

include/hip/hcc_detail/hip_complex.h
fixed loss of accuracy in hipCfma()
=> fixed loss of accuracy in hipCfma()

src/hip_hcc.cpp, src/hip_hcc_internal.h, src/hip_memory.cpp
Add 2D fallback to use copy kernel
=> Add 2D fallback to use copy kernel

include/hip/hcc_detail/hip_runtime_api.h, src/hip_memory.cpp
Depends on HCC [#1076](https://github.com/RadeonOpenCompute/hcc/pull/1076)
=> hipExtMallocWithFlags implementation

src/hip_memory.cpp
Handles hipMemcpyDeviceToDevice
=> Handle D2D in memcpy2D

include/hip/hcc_detail/hip_runtime.h
CUDA has __align__. Define eqivalent for hip-clang.
=> hip-clang: Add __align__

include/hip/hcc_detail/code_object_bundle.hpp
=> Append the ELF flags for sram-ecc and xnack to the target triple per code object

tests/src/runtimeApi/memory/hipMemcpyDtoDAsync.cpp
=> [dtest] Fix D2DAsync test

include/hip/hcc_detail/hip_runtime_api.h, include/hip/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime_api.h, src/hip_memory.cpp, tests/src/runtimeApi/memory/hipMallocManaged.cpp
Adds default functional - hipMemAttachGlobal flag- support of hipMallocManaged
=> Add hipMallocManaged default functional support

include/hip/nvcc_detail/hip_runtime_api.h
=> Fix hipPointerGetAttributes for NVCC

include/hip/hcc_detail/hip_vector_types.h
- Minor clean up to keep consistent function declaration.
=> [devfunc] Add necessary `__device__` and `__host__` attributes.

include/hip/nvcc_detail/hip_runtime.h
=> Fix symbol address issue on NVCC path

samples/2_Cookbook/0_MatrixTranspose/Readme.md, samples/2_Cookbook/10_inline_asm/Readme.md, samples/2_Cookbook/1_hipEvent/Readme.md, samples/2_Cookbook/3_shared_memory/Readme.md, samples/2_Cookbook/4_shfl/Readme.md, samples/2_Cookbook/5_2dshfl/Readme.md, samples/2_Cookbook/6_dynamic_shared/Readme.md, samples/2_Cookbook/7_streams/Readme.md, samples/2_Cookbook/9_unroll/Readme.md
Hi, 
Just fixed a few markdown errors I noticed while working though the samples.  
Thanks,
Nick
=> Markdown fixes & Whitespace cleanup for samples

hipify-clang/src/HipifyAction.cpp, tests/hipify-clang/unit_tests/samples/dynamic_shared_memory.cu, tests/hipify-clang/unit_tests/samples/static_shared_memory.cu
=> [HIPIFY][fix][#1109] Do not preserve extern __shared__ for IncompleteArrayType

tests/hipify-clang/unit_tests/samples/2_Cookbook/0_MatrixTranspose/MatrixTranspose.cpp, tests/hipify-clang/unit_tests/samples/2_Cookbook/7_streams/stream.cpp
+ Add additional checks for extern __shared__ due to [#1109]
=> [HIPIFY][tests] Add reverse engineered HIP sample "stream"

docs/markdown/CUDNN_API_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_DNN_API_functions.cpp, tests/hipify-clang/unit_tests/libraries/cuDNN/cudnn_convolution_forward.cu
+ Update cudnn_convolution_forward test accordingly
=> [HIPIFY][cuDNN] Add cudnnGetFilter4dDescriptor support

CMakeLists.txt
This is blocking HIP-Clang/HIP/HCC build.
=> Fix build failure due to hiprtc for HIP-Clang

tests/hipify-clang/unit_tests/samples/2_Cookbook/7_streams/stream.cpp, tests/hipify-clang/unit_tests/samples/2_Cookbook/8_peer2peer/peer2peer.cpp
=> [HIPIFY][tests] Add reverse engineered HIP sample "peer2peer"

hipify-clang/src/CUDA2HIP.cpp, hipify-clang/src/HipifyAction.cpp, tests/hipify-clang/unit_tests/samples/2_Cookbook/11_texture_driver/tex2dKernel.cpp
+ Add a corresponding reverse engineered sample tex2dKernel with texture template
=> [HIPIFY] Add device texture fetch functions support

docs/markdown/hip_kernel_language.md
Here are a few updates for the kernel language document that mentions Cuda features added in versions 9 and 10.
=> Update kernel language documentation

docs/markdown/CUDNN_API_supported_by_HIP.md, hipify-clang/README.md, hipify-clang/src/CUDA2HIP_DNN_API_functions.cpp, hipify-clang/src/CUDA2HIP_DNN_API_types.cpp
+ Update docs and README.md accordingly
=> [HIPIFY][DNN] Support of cuDNN 7.6.0

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/helpers.hpp, include/hip/hcc_detail/hip_runtime_api.h, include/hip/hcc_detail/program_state.hpp, src/hip_hcc.cpp, src/hip_module.cpp, src/program_state.cpp, src/program_state.inl
=> migrate more program_state logic from header into shared library (phase II)

src/hip_module.cpp
For 2.6 relesse till we resolve SWDEV-190701 properly.
=> HACK for SWDEV-173477/SWDEV-190701

samples/0_Intro/module_api/Makefile, samples/0_Intro/module_api/defaultDriver.cpp
Fix sample to use kernelargs for launch
=> Fix sample to use kernelargs for launch

samples/0_Intro/module_api/launchKernelHcc.cpp, samples/0_Intro/module_api/runKernel.cpp, samples/0_Intro/module_api_global/runKernel.cpp
Add cleanup code in module api samples
=> Add cleanup code in module api samples

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/hip_runtime.h, include/hip/hcc_detail/hip_runtime_api.h, src/hip_module.cpp, tests/src/runtimeApi/module/hipOccupancyMaxPotentialBlockSize.cpp
This version supports both CO v2 and v3.
=> Implement the hipOccupancyMaxPotentialBlockSize function

hipify-clang/src/main.cpp
=> [HIPIFY] Fix multiple input files support

samples/2_Cookbook/9_unroll/Readme.md, samples/2_Cookbook/9_unroll/unroll.cpp
Simplifying the unroll example in samples directory to remove the warning.
=> Adding new unroll example

src/hip_event.cpp, src/hip_memory.cpp, src/hip_peer.cpp, src/hip_stream.cpp
Fixes SWDEV-132169, SWDEV-132552, SWDEV-132794, SWDEV-132931, SWDEV-132970, SWDEV-135524, SWDEV-137442, SWDEV-137535, SWDEV-138479, SWDEV-138481, SWDEV-138799, SWDEV-141618.
=> Added missing NULL checks and corrected API return values

.gitignore, include/hip/hcc_detail/hip_runtime.h, include/hip/hcc_detail/hip_runtime_api.h
=> Adding fix to initialize a dim3 variable from blockIdx.

src/hip_hcc.cpp
=> Fix HIP_VISIBLE_DEVICES order

CMakeLists.txt, bin/hipcc, lpl_ca/ca.hpp, lpl_ca/common.hpp, lpl_ca/lpl.hpp, tests/src/deviceLib/hipMathFunctions.cpp, tests/src/deviceLib/hipTestHalf.cpp, tests/src/deviceLib/hipTestNativeHalf.cpp
GFX908 has completed upstream to llvm and clang.
=> Add GFX908 specific changes to HIP

docs/markdown/CUSPARSE_API_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_SPARSE_API_functions.cpp, hipify-clang/src/CUDA2HIP_SPARSE_API_types.cpp
+ Add undocumented but presented in cusparse.h functions since CUDA 10.1 Update 1
=> [HIPIFY][SPARSE] Sync cuSPARSE 10.1 - HIP - HIPIFY (Step 2 of 2)

tests/src/texture/hipNormalizedFloatValueTex.cpp
Added new testcase to validate char,uchar,short,ushort texture as normalized float.
=> Testcase to validate signed/unsigned char,short as normalized float

src/hip_module.cpp, tests/src/runtimeApi/module/hipFuncGetAttributes.cpp
Fix HIP init in hipFuncGetAttributes
=> Add HIP init in hipFuncGetAttributes

src/hip_module.cpp
Fix hip init in hipExtLaunchMultiKernelMultiDevice
=> Add hip init in hipExtLaunchMultiKernelMultiDevice

bin/hipcc
this allows user to override -std=c++14
=> Fix -std=c++14 for windows

hip-config-clang.cmake.in, hip-config-hcc.cmake.in
Fixes:
SWDEV-198421
SWDEV-198753
=> Partial revert of 'Add HSA_PATH to hip_Includes in cmake and hipconfig (#1260)'

tests/src/deviceLib/hipDoublePrecisionMathHost.cpp, tests/src/deviceLib/hipSinglePrecisionMathHost.cpp
Fixed compilation errors being observed on windows
=> Fixed compilation errors being observed on windows

include/hip/hcc_detail/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime_api.h, src/hip_memory.cpp
Equivalent to cuMemcpy2DAsync.
=> Add hipMemcpyParam2DAsync

CMakeLists.txt, bin/hipcc, bin/hipconfig
- Match HIP version with upcoming ROCm version
- Add githash to version string
=> Bump HIP version

docs/markdown/hip_porting_guide.md
Remove extra trailing `_` in platform defines
=> Fix HIP Platform defines

docs/markdown/CURAND_API_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_RAND_API_types.cpp, tests/hipify-clang/unit_tests/libraries/cuRAND/poisson_api_example.cu
+ Update CURAND_API_supported_by_HIP.md and test accordingly
=> [HIPIFY][cuRAND][#1257] Fix

docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Driver_API_functions.cpp, hipify-clang/src/CUDA2HIP_Driver_API_types.cpp, hipify-clang/src/CUDA2HIP_Runtime_API_functions.cpp, hipify-clang/src/CUDA2HIP_Runtime_API_types.cpp, tests/hipify-clang/unit_tests/samples/MallocManaged.cpp
+ Add mapping for corresponding data types
+ Add a test
+ Update docs
=> [HIPIFY] Add cudaMallocManaged -> hipMallocManaged

include/hip/nvcc_detail/hip_runtime_api.h
=> [HIP] Fix for hipArray_t failure on nvcc path

include/hip/hcc_detail/hip_runtime.h, src/hip_module.cpp
Post #1303 , this issue was exposed.
=> Fix undefined identifier issue for hipExtModuleLaunchKernel

tests/src/hipEnvVar.cpp, tests/src/hipEnvVarDriver.cpp, tests/src/runtimeApi/memory/hipMemcpy_simple.cpp, tests/src/runtimeApi/memory/hipMemoryAllocateCoherentDriver.cpp, tests/src/test_common.h
Common changes are made in test_common.h to be used by multiple dtests.
=> [dtests] refactor windows specific changes

bin/hipcc
=> [hipcc] Fix for uninitialized variables on nvcc path

src/hip_memory.cpp
Using HSA api for better performance
=> Using HSA API for hipMemsetAsync

include/hip/hcc_detail/code_object_bundle.hpp
=> Make Bundled_code_header visible for hipRTC usage

include/hip/hcc_detail/helpers.hpp
=> moving result_of_t to result_of

include/hip/hcc_detail/functional_grid_launch.hpp, samples/2_Cookbook/13_occupancy/Makefile, samples/2_Cookbook/13_occupancy/occupancy.cpp
Updated the  sample occupancy.cpp and Makefile according to the review comments.
=> [sample] add new cookbook sample - occupancy

include/hip/nvcc_detail/hip_runtime_api.h, src/hip_hcc.cpp
Updated missing hipErrorString and CudaErrorTohipError
Tracking bug SWDEV#148424
=> Updated hipErrorString and CUDAErrorTohipError

bin/hipify-perl, tests/hipify-clang/unit_tests/samples/axpy.cu
empty<<<1, 2>>> ( );       >>  hipLaunchKernelGGL(empty, dim3(1), dim3(2), 0, 0);
empty<<<1, 2, 0>>>();     >>
empty<<<1, 2, 0, 0>>>(); >>
instead of erroneous:    >> hipLaunchKernelGGL((empty), dim3(1), dim3(2), 0, 0, );
=> [HIPIFY][perl][#259] Fix

hipify-clang/src/CUDA2HIP_Perl.cpp, hipify-clang/src/CUDA2HIP_Python.cpp, hipify-clang/src/CUDA2HIP_Scripting.h, hipify-clang/src/StringUtils.cpp, hipify-clang/src/main.cpp
+ Move generating hipify-perl and hipify-python into separate namespaces and files
+ Move getAbsoluteFilePath and getAbsoluteDirectoryPath to StringUtils
=> [HIPIFY] Scripting related refactoring

hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h
+ Merge of cudaSymbolFuncCall and cudaReinterpretCastArgFuncCall matchers into a single cudaHostFuncCall matcher
+ More const std::string declarations
+ Formatting
=> [HIPIFY] HipifyAction refactoring

include/hip/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime_api.h, src/hip_hcc.cpp
=> [HIP] Add tccDriver info in hipDeviceProp [github#1433]

bin/hipify-perl, hipify-clang/src/CUDA2HIP_Perl.cpp
+ Minor hipify-perl clean-up
+ Minor CUDA2HIP_Perl refactoring
=> [HIPIFY] Generate more hipify-perl (continuation)

hipify-clang/src/CUDA2HIP_Perl.cpp
TODO: make statistics as much as similar to hipify-clang's
=> [HIPIFY][perl] Generate stat functions

docs/markdown/hip_profiling.md
=> [docs] Fix sample links in hip_profiling

bin/hipify-perl, hipify-clang/src/CUDA2HIP_Perl.cpp
+ Update hipify-perl accordingly
=> [HIPIFY][perl] Generate transformExternShared function

bin/hipify-perl, hipify-clang/src/CUDA2HIP_Perl.cpp
+ hipify-perl script is entirely generated by hipify-clang under an option -perl now
+ hipify-perl still has correctness gaps comparing to hipify-clang: they will be eliminated AMAP further
=> [HIPIFY][perl] Finishing with generation of hipify-perl

include/hip/hcc_detail/hip_runtime_api.h, src/hip_texture.cpp, src/hip_texture.h
Added support for -
- hipTexRefGetArray
- hipTexRefGetAddressMode
- hipTexRefGetAddress
=> Add texref get APIs support

hipify-clang/src/CUDA2HIP_Perl.cpp
+ Generated hipify-perl is unchanged
=> [HIPIFY] CUDA2HIP_Perl code clean-up and formatting

bin/hipify-perl, docs/markdown/CUSPARSE_API_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_SPARSE_API_functions.cpp, hipify-clang/src/CUDA2HIP_SPARSE_API_types.cpp
+ Update doc and hipify-perl accordingly
=> [HIPIFY][SPARSE] sync with hipSPARSE

src/hip_hcc.cpp
Requires not yet publicly released ROCr agent attribute.
=> Fix PCI Domain ID query

bin/hipify-perl, docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Driver_API_functions.cpp, hipify-clang/src/CUDA2HIP_Runtime_API_functions.cpp
+ Update hipify-perl accordingly
=> [HIPIFY] Sync with HIP

bin/hipify-perl, hipify-clang/src/CUDA2HIP_Perl.cpp, tests/hipify-clang/unit_tests/namespace/ns_kernel_launch.cu
+ Modify CUDA2HIP_perl for the fix
+ Add ns_kernel_launch.cu test
+ Update hipify-perl by hipify-clang -perl
=> [HIPIFY][#1487][fix] Translate correctly kernel names prefixed with namespace

hipify-clang/README.md
=> [HIPIFY][doc] Add a few words about hipify-perl

tests/src/hiprtc/hiprtcGetLoweredName.cpp, tests/src/hiprtc/hiprtcGetTypeName.cpp, tests/src/hiprtc/saxpy.cpp
Adding target resolution in hiprtc tests and reenable them.
=> Re enable test RTC

hipify-clang/CMakeLists.txt, hipify-clang/README.md
+ Update README.md accordingly
=> [HIPIFY][cmake] Make CMakeLists.txt compatible with default cmake 3.5.2 for Ubuntu 16.04

hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, tests/hipify-clang/unit_tests/libraries/CUB/cub_02.cu
+ Add cub_02.cu test
+ Partial fixes #1460
=> [HIPIFY][CUB][#1460] Implement cubFunctionTemplateDecl matcher

hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h
+ Separate out GetSubstrLocation function for finding substr SourceLocation in a given SourceRange
=> [HIPIFY] Refactor a couple of matcher functions

hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, tests/hipify-clang/unit_tests/libraries/CUB/cub_03.cu
=> [HIPIFY][CUB][#1460] Add "using namespace cub" translation support

docs/markdown/hip_profiling.md
Correction about disabled profiling support in pre-built binaries.
=> [docs] Update profiling doc

include/hip/hcc_detail/hip_runtime_api.h, src/hip_memory.cpp
Adds hipMemcpy2DFromArray and hipMemcpy2DFromArrayAsync equivalent to cudaMemcpy2DFromArray and cudaMemcpy2DFromArrayAsync.
=> Add hipMemcpy2DfromArray

src/program_state.inl
The lifetime of the buffer given to
hsa_code_object_reader_create_from_memory must exceed that of the
code object reader. We need to create a copy of the code object
binary memory (file) that is kept allocated until the code object
reader is destroyed.
=> Fix a code object memory corruption

hipify-clang/src/ArgParse.cpp, hipify-clang/src/ArgParse.h, hipify-clang/src/main.cpp
+ Pass it to clang if specified
=> [HIPIFY] Introduce --cuda-gpu-arch as hipify-clang's option

src/hip_hcc.cpp, src/hip_hcc_internal.h, src/hip_stream.cpp, tests/src/runtimeApi/stream/StreamAddCallback.cpp, tests/src/runtimeApi/stream/hipStreamAddCallbackCrossStream.cpp, tests/src/runtimeApi/stream/hipStreamAddCallbackMultiThread.cpp
1. Fixed hipStreamAddCallback() as requested in SWDEV#165185
2. Added unit test to test the behavior
=> [HIP] Fixed hipStreamAddCallback [SWDEV#165185]

hipify-clang/src/LLVMCompat.cpp, hipify-clang/src/LLVMCompat.h, hipify-clang/src/main.cpp
[Reason] It turned out that it is not so: 2 jobs are always
=> [HIPIFY][fix] Abandon canCompileHostAndDeviceInOneJob check for --cuda-compile-host-device option

bin/hipconfig
Change-Id: Id1e6eb222080a339af938212e74a52c39c305eab
=> Bump version to 3.0

tests/src/hiprtc/saxpy.cpp
Creating Pull Request to fix missing vector header file in saxpy.cpp.
=> Fixing compilation error in saxpy.cpp

include/hip/hcc_detail/hip_runtime_api.h, src/hip_event.cpp
- Added missing null check in hipEventSynchronize
- Minor correction in the Event API description
=> Added null check in hipEventSynchronize

include/hip/hcc_detail/hip_atomic.h, tests/src/deviceLib/hipSimpleAtomicsTest.cpp
- This reverts PR #1591 and follow-on PR #1695
=> Revert changes for atomic FADD support when address is in LDS

bin/hipify-perl, docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Driver_API_types.cpp, hipify-clang/src/CUDA2HIP_Runtime_API_types.cpp
+ Both Driver API and RT API are supported and synced with each other
+ Update *.md docs and hipify-perl accordingly
=> [HIPIFY] CUDA 10.2 support (data types only)

bin/hipify-perl, docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Driver_API_functions.cpp, hipify-clang/src/CUDA2HIP_Runtime_API_functions.cpp, hipify-clang/src/Statistics.cpp, hipify-clang/src/Statistics.h
+ Both Driver API and RT API are supported and synced with each other
+ Update *.md docs and hipify-perl accordingly
+ Add a new conversion type "virtual_memory", introduced in Dirver API
=> [HIPIFY] CUDA 10.2 (functions only)

hipify-clang/src/main.cpp
+ Implemented by using clang Driver infrastructure
[ToDo] Add tests for in-place hipification of multiple files
=> [HIPIFY][fix][#1246][#1655] Sort input files based on their dependency graph

hipify-clang/src/main.cpp
Needed for sorting input files to avoid clang errors on unsupported options
=> [HIPIFY] Add cleanupHipifyOptions functionality

include/hip/hcc_detail/hip_vector_types.h
There were multiple build failure issues reported. More details can be found SWDEV-215752 & 215966
=> Fix for windows dtest build failure

include/hip/hcc_detail/hiprtc.h, src/hiprtc.cpp
Sorry, my branch had some issues. This is the same as 1733
=> Fix the return type of demangle function so that its compatible across ABIs

docs/markdown/hip_kernel_language.md
I found it confusing when reading the doc seeing that the two arguments in <<<>>> are the same. Others may have the same question.
=> Fix minor explainations in the kernel guide

include/hip/hcc_detail/hip_complex.h
=> Fix rocFFT build failure

packaging/hip-nvcc.postinst, packaging/hip-nvcc.prerm
Fix hip-nvcc install warning on postinstall and prerm script
=> Fix install script syntax error

tests/src/runtimeApi/module/hipLaunchCoopMultiKernel.cpp
Simple test for hipLaunchCooperativeKernelMultiDevice API.
=> [dtest] RCCL multi device launch test

src/hip_clang.cpp
This is needed so that the right symbols are present if we want to use hip-clang with hip/hcc runtime
=> Implement __hipPushCallConfiguration/__hipPopCallConfiguration for hip_clang

packaging/hip-targets-release.cmake, packaging/hip-targets.cmake
Reverts ROCm-Developer-Tools/HIP#1831
=> Revert "Cmake package"

src/hip_peer.cpp
hipDeviceEnablePeerAccess returns success and adds peer into the list even if it is not accessible which creates problem in hipMalloc when it tries to share the ptr to peer device. 
Proposed change is to check the access status before updating the peer list and update only when it can access the peer.
=> Fix ihipEnablePeerAccess return if peer is not accessible

src/hip_module.cpp
=> [hip] Fix for bug introduced in #1770 when blockSize is non-power of 2

samples/1_Utils/hipDispatchLatency/Makefile, samples/1_Utils/hipDispatchLatency/hipDispatchEnqueueRateMT.cpp
Adds a sample to measure dispatch enqueue rate for multi thread multi stream dispatches.
=> [sample] Add hipDispatchEnqueueRateMT

include/hip/hcc_detail/device_functions.h
=> fix long shuffle implementations for windows

Jenkinsfile, bin/hipconfig
- Bump version to 3.2
- [ci] Enable tests on ROCm 3.1
=> bump version to 3.2

include/hip/hcc_detail/device_library_decls.h, include/hip/hcc_detail/hip_atomic.h
=> Expose support for non-returning atomic FADD

include/hip/hcc_detail/device_functions.h
=> Fix __sad signature match with Cuda

src/hip_hcc.cpp, src/hip_hcc_internal.h, src/hip_stream.cpp, tests/src/runtimeApi/stream/StreamAddCallback.cpp, tests/src/runtimeApi/stream/hipStreamAddCallbackCatch.cpp
=> fix hipStreamAddCallback, block future work on stream

include/hip/hcc_detail/hip_runtime_api.h
Correct URL for deprecated api list
=> [docs] Correct URL for deprecated api list

tests/src/deviceLib/hip_floatnTM.cpp
=> [dtest] Adding VectorTest

include/hip/hcc_detail/hip_vector_types.h
=> Add const qualifiers to HIP_vector_type unary arithmetic operators

docs/markdown/hip_debugging.md
=> [docs] Update hip_debugging.md

samples/0_Intro/module_api/defaultDriver.cpp, samples/0_Intro/module_api/launchKernelHcc.cpp, samples/0_Intro/module_api/runKernel.cpp, samples/0_Intro/module_api_global/runKernel.cpp, src/hip_module.cpp, src/hip_texture.cpp, tests/src/runtimeApi/module/hipModuleLoadDataMultThreaded.cpp
Fixed few memory leaks showed up in cppcheck scan.
=> Fix few memory leaks in HIP

include/hip/hcc_detail/device_library_decls.h, include/hip/hcc_detail/hip_atomic.h
Change-Id: I78d741cd1cde32057fff47599034099dbe5ed2da
=> Remove address_space(1) typecast and use __ockl_atomic_add_noret_f32

src/hip_memory.cpp
System where Peer2Peer access is not enabled hipMemcpyDtoD & hipMemcpyPeer throw exception. Added a fallback mechanism which will be slow but complete the copy.
=> Fix for Segfault seen in hipMemcpyDtoD [SWDEV-227444]

src/hip_event.cpp, src/hip_hcc_internal.h, tests/src/runtimeApi/event/hipEventElapsedTime.cpp
Fixes SWDEV-228636.
Also added a unit test to verify this.
=> hipEventElapsedTime should respect device

bin/hipify-perl, docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
Sync with: https://github.com/ROCm-Developer-Tools/HIPIFY/pull/102
Update hipify-perl accordingly
=> [HIPIFY][HIP][doc] Sync with HIPIFY's #102 (#2051)

bin/hipify-perl, docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
[HIPIFY][#143](https://github.com/ROCm-Developer-Tools/HIPIFY/pull/143) CUDA 11.0 Driver API support
Update hipify-perl accordingly
=> [HIPIFY][HIP][doc] Sync with HIPIFY's #143

bin/hipify-perl, docs/markdown/CUBLAS_API_supported_by_HIP.md, docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, docs/markdown/CUSPARSE_API_supported_by_HIP.md
[Reasons]
+ Sync with latest HIP ROCclr
+ Sync with latest hipSPARSE and hipBLAS
=> [HIPIFY][HIP][doc] Update all CUDA2HIP docs and perl script
