ROCm-Developer-Tools/HIP

src/hip_db.cpp, src/hip_hcc.cpp
It is observed several HIP-based applications are having issue when `HCC_OPT_FLUSH` is set to `1`. Before a proper fix is devised, turn off this optimization in this PR.
=> Disable HCC_OPT_FLUSH

Jenkinsfile, docker/dockerfile-build-ubuntu-16.04, docker/dockerfile-hip-ubuntu-16.04
HiP docker images should inherit the repo information from the hcc image,
so no need to duplicate in HiP again
=> [ci] Remove repo.radeon.com build-args; HiP CI unit tests running 

CMakeLists.txt
Cmake cache was being rebuilt on each build. This was being done
to update HIP_VERSION, HCC_VERSION, .hipInfo and .hipVersion.
However, rebuilding cache also re-runs HIT parser which is slow.
Removing the cache rebuild should speed up the build. But user
needs to explicitly rebuild the cache in case HIP_VERSION or
HCC_VERSION changes by calling "make rebuild_cache"
=> [cmake] No longer rebuild cmake cache on each build

Jenkinsfile, tests/src/hipEnvVar.cpp, tests/src/hipEnvVarDriver.cpp
This PR fixes indentation, binary path and adding wait on popen calls for the hipEnvVarDriver test.
=> Fix hipEnvVar test

src/hip_hcc.cpp
Optimizes null stream synchronization so it uses GPU-side dependency
resolution. Requires HCC __hcc_workweek__ > 17300.
=> Set HIP_SYNC_NULL_STREAM=0.

bin/hipcc
Existing logic has a bug. If user specifies targetA via commandline
options, while enumerator returns targetB, hipcc will create a fatbin
containing targets targetA and targetB. enumerator should only be used
when no target is specified by user (commandline or env var).
=> [hipcc] Cleanup amdgpu target logic

src/hip_context.cpp, src/hip_device.cpp, src/hip_hcc_internal.h
1) hipSetDevice sets a flag so that next call to hipCtxGetCurrent returns primary context on current device
2) hipCtxGetCurrent returns primary context on current device if TLS context stack is empty
3) hipCtxPopCurrent falls back to primary context on current device as default
4) hipCtxPushCurrent, hipCtxSetCurrent and hipCtxCreate reset the flag set in hipSetDevice
=> Updated context management logic:

include/hip/hcc_detail/hip_runtime.h, src/device_util.cpp, tests/src/deviceLib/hip_threadfence_system.cpp
Implement __threadfence_system as an atomic thread fence with the seq_cst memory order.
Add a new test for __threadfence_system.
=> implement __threadfence_system

src/hip_hcc.cpp, src/hip_memory.cpp
The GPU virtual address for texture memory needs to be aligned.
In hcc_am, a bigger buffer will be allocated for alignment purpose
and _unalignedDevicePointer is added in struct AmPointerInfo for
original allocated address.
=> [HIP Texture] The GPU virtual address for texture memory needs to be

tests/src/runtimeApi/event/record_event.cpp, tests/src/runtimeApi/stream/hipStreamSync2.cpp
Enabled these tests since HIP_SYNC_NULL_STREAM=0 for __hcc_workweek__ >= 17300
=> Enable hipStreamSync2 and record_event dtests

Jenkinsfile
The test machine updated its drivers.
Move deleting docker images into the try clause, don't treat failure to delete images
as a build failure
=> Update the nvidia volume driver version

include/hip/hcc_detail/hip_runtime.h, include/hip/nvcc_detail/hip_runtime.h
For now abort() prints back trace while exiting.
=> Device side assert support

bin/hipcc
Cent OS 7 has conflicts between its libc++ and libstdc++. Seems that we cannot use libstdc++ on Cent OS. This is related to SWDEV-131972 [ROCm CQE][Cent OS 7][G] Building any HIP sample giving an fatal error: 'bits/c++config.h'.
=> [CentOS7] Fix HIP sample hipInfo and other tests

src/hip_hcc.cpp
This would significantly improve performance for certain apps in kernel
selection logic.
=> Bump device major version from 2 to 3

Jenkinsfile
docker image names should be lowercase; Repo name sometimes use CamelCasing
=> Force organization name to be lowercase for docker image name

hipify-clang/src/Cuda2Hip.cpp
The LLVM APIs modify the input file in-place. To avoid overwriting the input file,
the original implementation was therefore copying the input to the output and
operating on the output. This fails, however, because it means relative includes
are being resolved relative to the output path.
To resolve this, I here change the behaviour to:
- Copy the input file to `<src>.hipify-tmp`
- Operate on that temporary file
- Move the temporary file to the output (which will overwrite the input if we're
in in-place mode).
This strategy has the added advantage that you won't corrupt the input source file
if the program crashes while operating in in-place mode.
=> [HIPIFY] Alter output file behaviour slightly

src/hip_hcc.cpp
- re-initialize the printf buffer in HCC RT after resetting the am memory tracker
- this will fix several HIP directed test failures observed with a recent HCC compiler
- this PR depends on  https://github.com/RadeonOpenCompute/hcc/pull/508
=> hipDeviceReset(): make sure to reinitialize the printf buffer in hcc RT

hipify-clang/CMakeLists.txt
After switching HIPIFY_CLANG_TESTS on by default it turned out that standalone build is broken.
Change relies on an assumption that hipify-clang is in HIP folder as it is so for now, but it will be changed with moving of hipify-clang to a separate github repo.
=> [HIPIFY] cmake: fix standalone build

hipify-clang/src/Cuda2Hip.cpp
Apparently a couple of those APIs changed in clang 5, not 4.
Got an email from a disgruntled AMD person about this ;)
=> Tweak some version numbers in clang version compatibility checks

hipify-clang/CMakeLists.txt
Otherwise LLVM will be searched in system folders.
=> [HIPIFY][fix] cmake: NO_DEFAULT_PATH is strongly needed in find_package for LLVM

include/hip/hip_runtime_api.h
This will yield a compiler warning any time you discard an error
return value from an API call.
Some thoughts:
- Should we move the definition of `__HIP_NODISCARD` into `hip_common.h` - it
might well prove useful elsewhere, after all.
- A very common pattern (at least in CUDA code) is to wrap every API call in
a macro that implements some flavour of "If exception, crash". Perhaps hip
could provide one of those out of the box as a convenience?
- Perhaps there could be a macro that, when set, causes hip errors to propagate
as exceptions instead of this C-style API? I guess that would be part of a
more general C++ API for hip (which would, admittedly, slightly defeat the
point of being a close match to CUDA. But CUDA is very much clunky to use in
some situations)...
=> Add [[nodiscard]] attribute to hipError_t in C++17 mode

hipify-clang/src/Cuda2Hip.cpp, tests/hipify-clang/axpy.cu
See commit messages for detailled explanations. This partially fixes #207,
effectively allowing hipify to handle all preprocessor interactions
except false conditionals correctly.
It will still be forced to inline macros in silly cases, but this should
handle anything you're likely to get in sane code. It won't cope with,
for example:
```c++
#define silly x)
kernelCall<<<1, 1>>>(silly
```
... But if you write code like that, I think you deserve to have hipify
shout at you ;)
=> [HIPIFY] Handle unconditional preprocessor directives far better

src/hip_device.cpp, src/hip_hcc.cpp, src/hip_hcc_internal.h, src/hip_module.cpp, src/hip_stream.cpp
Also refactor some miuses of ihipLogStatus, these should only be in top-level
HIP APIs and should be paired with HIP_API_INIT calls.
=> Add ns-level timer for HIP API routines

bin/hipcc, src/hip_module.cpp
- hipcc has to pass the -stdlib=libc++ to hcc
- remove usage of constexpr pair ctor since libc++ doesn't enable it under C++11
=> various fixes for centos/rhel

tests/src/context/hipMemsetD8.cpp, tests/src/deviceLib/hipTestDevice.cpp, tests/src/deviceLib/hipTestDeviceDouble.cpp, tests/src/experimental/xcompile/hipxxKer.cpp, tests/src/kernel/hipLanguageExtensions.cpp, tests/src/kernel/hipTestMemKernel.cpp, tests/src/stress/hipStressKernel.cpp
This corrects some interesting choices that were present in the HIP unit 
tests such as e.g. de-allocating memory allocated with new[] using free. 
All of these were identified via cppcheck.
=> Test cleanup

src/hip_event.cpp, src/hip_hcc.cpp, src/hip_hcc_internal.h, src/hip_stream.cpp
Events are now thread-safe using similar critical-section architecture as streams and contexts.  This is important to support cases where the same event is recorded multiple times, potentially from different threads.
=> Event thread safe

tests/README.md, tests/hit/HIT.cmake, tests/hit/parser
Cmake supports several builtin command-line tools. These tools can
now be specified as part of the HIT block. These commands will be
run during cmake configure step.
=> [hit] Add support for cmake commands as part of test infra

src/grid_launch.cpp, src/hip_context.cpp, src/hip_hcc.cpp
Logging status of hipCtxSynchronize was missing
Test if hip profiling is active for MARKER_END in ihipPostLaunchKernel
Add MARKER_END after the completion of a kernel launched through
the "grid launch"
=> Fix missing MARKER_END

hipify-clang/src/CUDA2HipMap.cpp
I'm particularly running into issues with `driver_types.h` in real
CUDA code...
=> [HIPIFY] Add hipify mappings for all CUDA headers that have HIP equivalents

src/device_functions.cpp
This fixes some outright quaint choices made when implementing HIP's bitwise conversion functions, by using simple `reinterpret_cast`s, as is idiomatic. These functions are supposed to be re-entrant, correct and efficient. Sadly, they were neither: they hid a massive race condition against a value stored in global memory, which means that they were also unreasonably slow if they ever managed to be correct, and relied on union based type punning which is in a grey area of the standard. It is difficult to ascertain what may have been the reason for coming up with this quirky solution.
=> Fix curious bitwise conversions.

src/device_util.cpp, src/math_functions.cpp
Replace archaic use of interesting homebrew functionality with calls to the HC maths library. 
This fixes a hang observed when building hipTestDeviceDouble.
=> Fix hang by purging archaisms

include/hip/hcc_detail/program_state.hpp, src/hip_hcc_internal.h, src/hip_module.cpp, src/hsa_helpers.hpp, src/program_state.cpp
This is primarily intended as an additional cleanup of the module functionality, in the aftermath of adopting module based dispatch. The main effort was associated with refactoring the questionable ihipModuleGetSymbol. It was quaintly written and misleading, in that it had little to do with getting symbols, and was exactly retrieving a kernel object. Error handling is modified so as to reduce branching depth. Functions which serve as interfaces to the HSA RT are moved in a separate helper header. Code object readers are properly deleted. Some leftover dead functionality pertaining to associating namespace scope variables with their allocated memory is removed. Executable loading is changed to use a string which holds the ELF image of the code object being loaded, thus avoiding some corner …
=> Clean up kernel retrieval code / module management

tests/src/deviceLib/hipDeviceMemcpy.cpp, tests/src/deviceLib/hipFloatMath.cpp, tests/src/deviceLib/hipFloatMathPrecise.cpp, tests/src/deviceLib/hipSimpleAtomicsTest.cpp, tests/src/deviceLib/hipTestDevice.cpp, tests/src/deviceLib/hip_anyall.cpp, tests/src/kernel/hipLanguageExtensions.cpp, tests/src/runtimeApi/memory/hipMemcpy.cpp, tests/src/runtimeApi/memory/hipMemcpyPeer.cpp, tests/src/runtimeApi/memory/p2p_copy_coherency.cpp, tests/src/runtimeApi/stream/hipStreamAddCallback.cpp
Fix warnings (related to unused variables and like) in these tests:
tests/src/deviceLib/hipDeviceMemcpy.cpp              | 2 +-
tests/src/deviceLib/hipFloatMath.cpp                 | 2 +-
tests/src/deviceLib/hipFloatMathPrecise.cpp          | 2 +-
tests/src/deviceLib/hipSimpleAtomicsTest.cpp         | 2 +-
tests/src/deviceLib/hipTestDevice.cpp                | 4 ----
tests/src/deviceLib/hip_anyall.cpp                   | 2 +-
tests/src/kernel/hipLanguageExtensions.cpp           | 8 --------
tests/src/runtimeApi/memory/hipMemcpy.cpp            | 2 --
tests/src/runtimeApi/memory/hipMemcpyPeer.cpp        | 1 -
tests/src/runtimeApi/memory/p2p_copy_coherency.cpp   | 1 -
tests/src/runtimeApi/stream/hipStreamAddCallback.cpp | 3 +++
=> [nvccWarnings] Fix warnings seen with dtests on nvcc path

Jenkinsfile
This enables us to remove the driver version from startup string
=> Upgrade to nvidia-docker2 for CUDA testing

hipify-clang/src/HipifyAction.cpp, tests/hipify-clang/headers_test_01.cu, tests/hipify-clang/headers_test_02.cu
// hipified to #include<hip/hip_runtime.h>
#include<cuda.h> // 1st cuda main include (Driver API)
// to eliminate
#include<cuda_runtime.h> // 2nd cuda main include (Runtime API)
HIP has one header hip_runtime.h for both CUDA APIs, thus second cuda main include directive is eliminated entirely.
=> [HIPIFY][FIX][#306] Eliminate second cuda main include directive

hipify-clang/CMakeLists.txt
+ Misc: Python ver. min 2.7, do not find socat on Win.
=> [HIPIFY][cmake] Version compatibility checks of CUDA and clang are added

tests/hipify-clang/lit.site.cfg.in
Env. var NVCUDASAMPLES_ROOT is changed to NVCUDASAMPLESX_Y_ROOT where X - major ver, Y - minor ver.
Reason: NVCUDASAMPLES_ROOT contains path to CUDA SDK installed last, while NVCUDASAMPLESX_Y_ROOT contains samples of the same version as of CUDA_TOOLKIT_ROOT_DIR.
=> [HIPIFY][tests][win] CUDA samples root env. var is changed

tests/src/runtimeApi/device/hipGetDeviceAttribute.cpp
Enable hipGetDeviceAttribute on nvcc since the issue reported earlier is now fixed
=> [nvcc] Enable hipGetDeviceAttribute

tests/hipify-clang/axpy.cu, tests/hipify-clang/cudaRegister.cu, tests/hipify-clang/square.cu
As HIP has started to support vanilla CUDA syntax for threadIdx, blockIdx, blockDim and gridDim.
Other CUDA builtins are not tracked for now.
=> [HIPIFY][tests] Remove checks on cudaBuiltins

hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, tests/hipify-clang/headers_test_03.cu, tests/hipify-clang/headers_test_04.cu, tests/hipify-clang/headers_test_05.cu
If in source CUDA file main header (cuda_runtime.h or cuda.h) is not presented, corresponding HIP main header (hip_runtime.h) should be explicitly included in output hipified file.
[Algorithm]
1. If #pragma once is presented, HIP main header should be placed just after it;
2. Otherwise if any other (not CUDA main) header is presented, HIP main header should be placed just before it;
3. Otherwise HIP main header should be placed in the beginning of output file.
P.S.
There might be one more situation when #ifndef #define ... #endif guard for the entire file is presented (make sense for *.h, *.hpp, *.cuh files). In this case HIP main include should be placed just after such #ifdef, or after #pragma once, if it is also presented. This situation will be handled in a separate change.
=> [HIPIFY][fix][#211] Algorithm for explicit insert of hip include directive

hipify-clang/src/HipifyAction.cpp
File location have to be verified, otherwise location of the first found '#pragma once' in any included header even system will be erroneously handled, which might lead to attempt to including hip_runtime.h in it.
=> [HIPIFY][fix] Fix PragmaDirective

Jenkinsfile, include/hip/hcc_detail/code_object_bundle.hpp
with ::Bundled_code_header constructor
Disabling hipPrintfKernel test from CI
=> Fixing rocblas build failure

include/hip/hcc_detail/code_object_bundle.hpp
originally a patch to fix a build issue on RHEL 7 but actually replacing `insert` with `assign` here makes the code a bit more concise, see HCC PR  https://github.com/RadeonOpenCompute/hcc/pull/608
=> use assign rather than insert

docs/markdown/hip_debugging.md
This PR is to fix a typo in the hip_debugging doc.
=> Update hip_debugging.md on typo of chicken bits

docs/markdown/CURAND_API_supported_by_HIP.md, hipify-clang/src/CUDA2HipMap.cpp, hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, hipify-clang/src/Statistics.cpp, hipify-clang/src/Statistics.h, tests/hipify-clang/cuRAND/benchmark_curand_generate.cpp, tests/hipify-clang/cuRAND/benchmark_curand_kernel.cpp, tests/hipify-clang/cuRAND/cmdparser.hpp, tests/hipify-clang/headers_test_09.cu, tests/hipify-clang/lit.cfg
Due to support of cuRAND headers.
+ compound test on all headers is added;
+ missing entities are added with updating the doc;
+ a couple cuRAND tests are added (https://github.com/ROCmSoftwarePlatform/rocRAND/tree/master/benchmark):
- the following CUDA entities are still unsupported by hipRAND:
curandMakeMTGP32Constants
curandMakeMTGP32KernelState
curandGetDirectionVectors32
curandDirectionVectorSet_t
CURAND_DIRECTION_VECTORS_32_JOEKUO6
curandStateSobol64_t
curandStateScrambledSobol64_t
curandGenerateLongLong
- and the following - by HIP:
cudaRuntimeGetVersion
- those entities are handled by CHECK-NOT directive for now.
=> [HIPIFY] InclusionDirective refactoring

hipify-clang/src/main.cpp
/srv/HIP/hipify-clang/src/main.cpp:134:19: error: no member named 'dbgs' in namespace 'llvm'
DEBUG(llvm::dbgs() << "Skipped some replacements.\n");
~~~~~~^
=> [HIPIFY][fix] Build against llvm 3.8.0 fixed - missing include

tests/src/p2p/hipPeerToPeer_simple.cpp, tests/src/runtimeApi/device/hipGetDeviceAttribute.cpp
Enable this on on nvcc. on hipcc it is crashing in a mGPU, non-peer scenario. Looks like that needs to be fixed.
=> [nvccTests] Enable hipPeerToPeer_simple on nvcc

bin/hipconfig
llc is now placed under $HCC_HOME/bin, instead of $HCC_HOME/compiler/bin.
=> Change hipconfig to adopt new location of llc

Jenkinsfile
Continue testing against ROCm 1.6.4 until we have a stable ROCm 1.7.x docker image
=> [ci] Continue testing against ROCm 1.6

include/hip/hcc_detail/texture_functions.h
when compiling with a newer hcc.  This is
due to a recent change to address space
mapping in the amdgpu compiler backend.
=> Change constant address space to 4

tests/src/texture/hipTextureRef2D.cpp
On HIP/HCC, passing of texture object as kernel argument is no longer required.
=> Remove textureObj kernel argument for HIP/HCC path

src/code_object_bundle.cpp
This was introduced in recent xnack changes naming changes which affected our offload bundler. This patch will fix issues in HIP samples, ROCR tests, and others. Related to internal issues SWDEV-150756, SWDEV-149306. Also requires HCC PR https://github.com/RadeonOpenCompute/hcc/pull/692
=> Fix new gfx target naming convention

include/hip/hcc_detail/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime_api.h, src/hip_memory.cpp, tests/src/runtimeApi/memory/hipMemset2D.cpp
-hipMemset2DAsync support on HIP/HCC and HIP/NVCC paths
-Test for hipMemset2D and hipMemset2DAsync 
- Fixed dst NULL check in ihipMemset
=> Added hipMemset2DAsync support

src/hip_memory.cpp
Fixed the issue for ::hipMalloc3DArray.cpp gives seg. fault when NULL or 0 is passed as first parameter.
Verified the case in my local machine and also observed that directed tests have no impact with this fix.
=> SWDEV-141024

include/hip/hcc_detail/math_functions.h, src/hip_fp16.cpp, src/math_functions.cpp, tests/src/deviceLib/hipMathFunctions.cpp, tests/src/deviceLib/hipTestHalf.cpp
This change fixes the following bugs that were discovered while debuggnig TF unit test failures (cwise_ops_test)
1. __hisinf and __hisnan routines
Both had incorrect implementations.
2. abs
A "long long" (64bit int) version was missing, resulting in the 32bit version being used for 64bit ints (which resulted in incorrect results, when the value passed in was outside the 32bit int range)
3. lgamma
We seemed to have a custom version for the 'double' datatype (which was giving incorrect results). Replaced it with a call to the 'double' version of the underlying 'hc::precision_math::lgamma'
=> Checkin to fix bugs in math functions.

CMakeLists.txt
These architectures are no longer supported. Should not compile for them.
=> Remove unsupported targets gfx801 and gfx802

src/hip_memory.cpp
Null checks added for hipmallocpitch and hipmemcpy apis. Verified the fixes in the local machine , they worked fine. Also as suggested earlier, only NULL checks points added and not the zeros.
=> Null checks added for hipmallocpitch and hipmemcpy apis

docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HipMap.cpp
Execution Control [deprecated since 7.0]:
cudaConfigureCall -> hipConfigureCall
cudaLaunch -> hipLaunchByPtr
cudaSetupArgument -> hipSetupArgument
Surfaces (partially):
cudaSurfaceObject_t -> hipSurfaceObject_t
cudaSurfaceBoundaryMode -> hipSurfaceBoundaryMode
cudaCreateSurfaceObject -> hipCreateSurfaceObject
cudaDestroySurfaceObject -> hipDestroySurfaceObject
Memory Management:
cudaMemset2DAsync -> hipMemset2DAsync
=> [HIPIFY] Sync with HIP (Execution Control, Surfaces, Memory)

docs/markdown/hip_terms.md
=> Add space between `###` and `Notes` in hip_terms

hipify-clang/src/CUDA2HipMap.cpp
- not finished yet.
- based on https://github.com/ROCmSoftwarePlatform/hipDNN.
- testing on https://github.com/baidu-research/DeepBench - almost pass, except cusparse (not supported yet).
- started testing of examples from libcudnn7-dev_7.1.3.16-1+cuda8.0_amd64 package.
=> [HIPIFY][DNN] support of cuDNN 7.1.3 - continuation 2

src/device_functions.cpp
Fixes #356.
The new code is taken verbatim from [ROCm-Device-Libs](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/master/opencl/src/integer/int.h#L70), i.e. the ROCm OpenCL implementation of these very same functions. Hence I hope there are no licensing issues or anything, as both projects are part of the ROCm effort.
Let me know if I should add tests somewhere; I haven’t looked into that because the previous implementation was apparently untested as well.
Cheers!
=> Provide correct __mul64hi and __umul64hi builtins, using code from ROCm-Device-Libs

include/hip/hcc_detail/hip_runtime.h, include/hip/hip_runtime_api.h
This is to fix the compilation failure for the following test:
```
#include "hip/hip_runtime.h"
#include <assert.h>
#include <stdio.h>
// Use fixed value for __FILE__ so assert message does not depend on
// the actual path to the file during compilation..
#define __FILE__ "assert.cu"
__global__ void kernel() {
// Our reference output contains the line number of this assert() call; be
// careful when modifying the parts of this file above this line.
assert(false);
}
int main() {
hipLaunchKernelGGL((kernel), dim3(1), dim3(1), 0, 0, );
hipError_t err = hipDeviceSynchronize();
if (err != hipErrorAssert)
return err;
return 0;
}
```
=> Add __assert_fail, __device_trap and hipErrorAssert for clang

CMakeLists.txt, hip-config.cmake.in
This adds cmake targets for host and device to make it easier to link against the host or device version of the library.
=> Add host and device targets

src/hip_memory.cpp
Fixes SWDEV-153754 & SWDEV-154178.
=> hipMemcpy returns success if sizeBytes is 0.

include/hip/hcc_detail/hip_runtime_api.h, include/hip/hcc_detail/program_state.hpp, src/functional_grid_launch.inl, src/hip_module.cpp, src/program_state.cpp, tests/src/runtimeApi/module/hipFuncGetAttributes.cpp
This adds support for hipFuncGetAttributes but, more profoundly, percolates the whole amd_kernel_code_t header structure and makes it accessible from a Kernel_descriptor. This should help with a number of other APIs. Note that this is not fully symmetric with NVIDIA - theirs works on the __device__ side, whereas ours does not yet do so. One of the HIP experts should actually carefully review the mapping from CUDA attribute to HIP attribute, the currently proposed one is minimalistic.
=> Add support for the hipFuncGetAttributes interface.

include/hip/hcc_detail/math_functions.h
Adding overloads for abs that are found in cuda's math_functions.
Changes to cpp source here: https://github.com/ROCm-Developer-Tools/HIP/pull/472
=> Adding double/long int signatures for abs

bin/hipcc
They are replaced by --cuda-gpu-arch= options elsewhere
=> Drop --amdgpu-target= options for hip-clang

src/hip_memory.cpp
Fix retrieved locked ptr offset. This fixes accuracy differences seen with #484.
=> Fix retrieved locked ptr offset

src/hip_memory.cpp
Temporary PR for now, to test dtrsm issues seen while using hipMemcpy2DAsync
=> Use memcpy kernel for all pinned memory cases in hipMemcpy2DAsync

include/hip/nvcc_detail/hip_complex.h
__device__ __host__ static inline hipDoubleComplex hipCmul(hipDoubleComplex p, hipDoubleComplex q) was missing in include/nvcc_detail/hip_complex.h
=> added missing hipCmul() to nvcc_detail/hip_complex.h

cmake/FindHIP.cmake
e.g. `$<INSTALL_PREFIX:include>`
=> Properly handle (empty) cmake generator expression

include/hip/hcc_detail/program_state.hpp, src/functional_grid_launch.inl, src/program_state.cpp
This PR tries to re-initialize HIP runtime data structures in program_state.cpp. In applications such as TensorFlow it was evident that HIP kernels within shared libraries may not be identified if they are loaded later after initialization by dlopen(). Instead of raising an exception immediately we re-initialize data structures within program_state.cpp with a rebuild flag.
=> HIP program state re-initialization logic

include/hip/hcc_detail/hip_complex.h
These changes are required by hip-clang for compiling Tensorflow 1.3 and has been tested with it.
=> Fix hip_complex.h

src/hip_memory.cpp
Reverts ROCm-Developer-Tools/HIP#521
The issue observed is resolved by https://github.com/RadeonOpenCompute/hcc/pull/771
=> Revert "Use memcpy kernel for all pinned memory cases in hipMemcpy2DAsync"

src/hip_texture.cpp
Fixed offset null check in bind texture functions. Fixes SWDEV-155872.
=> Fixed offset null check in bind texture functions

tests/src/deviceLib/hip_mbcnt.cpp
Ctest did not catch this test failure. When running this test manually before typo, I got __mbcnt_hi() FAILED! . This fix will fix this test for HCC and HIP clang path.
=> Fix hip_mbcnt test typo

hipify-clang/src/LLVMCompat.h, hipify-clang/src/main.cpp
In LLVM 7.0 DEBUG(X) was deleted, LLVM_DEBUG(X) should be used instead.
=> [HIPIFY] Add DEBUG(X) macro compatibility

include/hip/hcc_detail/hip_runtime.h
Header math_functions.h should be included after including __clang_cuda_math_forward_declares.h to avoid warning: attribute declaration must precede definition.
=> [HIPClang] Switch ordering on math functions

include/hip/hcc_detail/hip_vector_types.h
This is required for PyTorch which runs into an issue with narrowing types. Requires an explicit cast.
=> Fix explicit cast required

bin/hipcc
Add support of environment variable HIP_VDI_HOME.
By setting environment variable HIP_VDI_HOME to the distribution directory of HIP/VDI, hipcc
will choose proper include and lib path for hip-clang.
=> Let hipcc use proper include and lib path for HIP/VDI

tests/src/deviceLib/hip_anyall.cpp, tests/src/deviceLib/hip_ballot.cpp
I'm not sure why hip_anyall and hip_ballot returned success in failed cases. It should return failure when it fails.
=> Fix return EXIT_FAILURE if ballot or anyall fails

tests/src/kernel/hipLaunchParm.cpp
- Uses c++11 features. Added it to nvcc options
- Arguments for some kernels exceeded 4096 bytes which is the limit
imposed by nvcc. Reduced BLOCK_DIM_SIZE to 512 to handle this
- Fixed compilation issues on nvcc path
=> [tests] Fixed hipLaunchParm test on nvcc path

include/hip/hcc_detail/hip_runtime.h, include/hip/hcc_detail/texture_functions.h
Include texture_functions.h on HIP-Clang path. Use HIP vector types instead of hc::short_vectors for texture_functions, and remove HCC headers.
=> Enable HIP texture functions with HIP vector types

src/hip_hcc.cpp, src/hip_memory.cpp
When shareWithAll memory (e.g., host memory) is allocated, set appId
in hc::AmPointerInfo to -1 to indicate that this memory is not mapped
to any device.  Peer checking in ihipStream_t::canSeeMemory is not
necessary if memory is shared with all devices.  Thus, it is skipped.
Note that earlier host memory is always mapped to device 0 and HIP
always performs peer checking for all kinds of hipMemcpy.  Since the
peer checking process requires context locking, hipMemcpy from/to host
memory always grabs device 0's context lock.  Therefore, if there is
another thread holding the context lock of device 0 (e.g.,
hipDeviceSynchronize on device 0), hipMemcpy will have to wait for the
lock until it can actually perform memcpy.  This can significantly
deteriorate execution performance.
Signed-off-by: …
=> Remove device mapping from shareWithAll memory

include/hip/hcc_detail/program_state.hpp, src/functional_grid_launch.inl, src/program_state.cpp
HIP PR#457 has been identified not only breaks 1 test case in PaddlePaddle, but also at least 5 unit tests in TensorFlow. After some consideration it should be abandoned.
Propose to change the default HIP runtime behavior so kernel symbol resolution is deferred until 1st kernel launch, instead of initialization before main(). This would be filed as separate PR.
For benchmarking programs which requires low setup time, implement an env var to reinstate eager initialization. This would be filed as separate PR by @sunway513.
=> Revert pr457

lpl_ca/lpl.hpp, samples/0_Intro/module_api/runKernel.cpp, samples/0_Intro/module_api_global/runKernel.cpp, samples/2_Cookbook/11_texture_driver/texture2dDrv.cpp
This change is for generating the output code-object file as application defined. For example , 
"--genco test.cpp -o test.code " should generate output file as "test.code".
=> Remove adipose extension from genco output

bin/hipcc, include/hip/hcc_detail/hip_runtime.h
This is for debugging legacy HIP applications which relies on some HCC features and work item functions.
=> Add HCC compatibility mode for hip-clang

CMakeLists.txt
We want to avoid linking with hc:: link libraries when building hip-clang
=> Enable HIP_COMPILER to choose HIP-Clang lib links

include/hip/hcc_detail/math_functions.h, include/hip/math_functions.h, tests/src/deviceLib/hipTestIncludeMath.cpp
This fixes build failure in TensorFlow 1.8 for HCC
=> Fix declaration conflict when hip/math_functions.h is included first

src/program_state.cpp
This PR changed the HIP default behavior and disabling the startup loader by default.
Users can turn it on by setting the environment variable as follows:
`export HIP_STARTUP_LOADER=1`
If the environment variable is not set or is set to other values, including '0', the startup loader will be disabled.
=> Disable startup loader by default and guard with env var

include/hip/hcc_detail/device_functions.h, tests/src/deviceLib/hip_bitextract.cpp, tests/src/deviceLib/hip_bitinsert.cpp
This patch is needed for building TensorFlow 1.8 and rocPRIM with hip-clang.
=> Add bitextract and bitinsert functions

include/hip/hcc_detail/hip_complex.h
Older gcc, e.g., 5.x, see an ambiguity in some calls. Example error
output as seen with gcc 5.5:
In file included from benchmark_wino.cpp:1:
In file included from ./miopen.hpp:13:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/regex:38:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/algorithm:62:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/bits/stl_algo.h:66:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/random:51:
/usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/bits/random.tcc:1324:27: error: call to 'abs' is ambiguous
const double __y = -std::abs(__n) * __param._M_sm - 1;
^~~~~~~~ …
=> Add keyword 'explicit' to avoid ambiguity

include/hip/hcc_detail/hip_fp16.h
@AlexVlx has provided this idea for undefined symbol errors in pytorch.
CC: @iotamudelta
=> added __host__ to float2half and half2float functions.

bin/hipcc
If obj files in linker response file contains device code, pass them to hip-clang, otherwise keep them in the linker response file.
This patch is required to build TensorFlow 1.8 with hip-clang.
=> Let hipcc handle obj files in linker response file for hip-clang

include/hip/hcc_detail/hip_runtime.h, include/hip/hcc_detail/math_functions.h
To fix min function being ambiguous in TF1.8 on HIP/HCC, let's use templates to enable more types for min and max functions. Let's keep everything the same for HIP-Clang path for now.
=> Use templates for min to prevent ambiguity

bin/hipcc
rocRAND assumes hipcc linking with -lpthread -lm by default.
=> Let hipcc link -lpthread -lm by default

include/hip/hcc_detail/hip_fp16.h
This is required if we want to move to LLVM5 as a base compiler for PyTorch
=> Only LLVM6 and higher contain the necessary intrinsics.

include/hip/hcc_detail/device_functions.h, include/hip/hcc_detail/hip_runtime.h, include/hip/hcc_detail/math_functions.h
This patch is needed for building TensorFlow 1.8 with hip-clang.
=> Fix build failure of hipTestHalf and hipTestIncludeMath for hip-clang

include/hip/hcc_detail/math_functions.h
static is already in __DEVICE__, so should be removed.
=> Silent warnings about duplicate static keyword

CMakeLists.txt, hip-config-clang.cmake.in, hip-config-hcc.cmake.in
The state of HIP_COMPILER is not passing into config files, therefore config files cannot use if statements to determine dependency. For HIP-Clang, we should remove find_dependency(hcc), so we create separate config files depending on compiler path. This fixes issue in apps that uses hip-config.cmake.
This also fixes blocking issue in MIOpen build from HIP PR https://github.com/ROCm-Developer-Tools/HIP/pull/633
=> Create separate config files for hcc and clang

tests/src/deviceLib/hipFloatMath.cpp
Device library has removed the non-default-rounded functions, so hipFloatMath will fail to build. These include the removal of __ocml_sqrt_rte, __ocml_sqrt_rtn, __ocml_sqrt_rtp, and __ocml_sqrt_rtz. As seen here: https://github.com/RadeonOpenCompute/ROCm-Device-Libs/commit/2fc04e10e1354edee331ce700f98a60f8255effb . Disable these function tests for now, until they are re-enabled, or deleted completely.
=> Disable non-default-rounded functions

docs/markdown/CUBLAS_API_supported_by_HIP.md, docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HipMap.cpp
TODO (hipBLAS/HIP): rename hipblasDatatype_t to hipDataType_t and move it from hipBLAS to HIP, as Data types are used not only in BLAS library.
=> [HIPIFY][BLAS] Add support of hipblasGemmEx and corresponding types

src/hip_memory.cpp
Return hipSuccess when sizeBytes=0 in hipMemset
=> Return hipSuccess when sizeBytes=0 in hipMemset

include/hip/hcc_detail/hip_vector_types.h
There was a missing long in the declaration for [u]longlongN types.
=> Fix hip_vector_types.h for long long vectors

bin/hipcc
hip-clang by default assumes -fno-gpu-rdc, therefore requires
--hip-device-lib-path by default.
=> Let hipcc add --hip-device-lib-path by default for hip-clang

include/hip/hcc_detail/program_state.hpp, src/functional_grid_launch.inl, src/program_state.cpp
This PR tries to re-initialize HIP runtime data structures in program_state.cpp. In applications such as TensorFlow it was evident that HIP kernels within shared libraries may not be identified if they are loaded later after initialization by dlopen(). Instead of raising an exception immediately we re-initialize data structures within program_state.cpp with a rebuild flag.
In ROCm 1.9 the behavior of HIP runtime was changed so GPU kernel discovery is carried out upon the 1st GPU kernel invocation. That helped quite a few TensorFlow unit tests as well as PaddlePaddle tests. But it turns out there are additional TensorFlow-based applications and libraries (example: RCCL) which would load additional shared libraries *AFTER* TensorFlow is initialized, and thus logic in this PR is required to …
=> HIP program state re-initialization logic (take 2)

include/hip/hcc_detail/math_functions.h
Using llvm_amdgcn builtin fails to produce accurate values, we should move to using the ocml device library versions.
=> Use sinf and cosf from ocml device libs

hipify-clang/CMakeLists.txt
[Reason]
Avoid cmake error occurred when mixing signatures with AddLLVM.cmake
[Error]
CMake Error at CMakeLists.txt:26 (target_link_libraries): The keyword signature for target_link_libraries has already been used with the target "hipify-clang".
All uses of target_link_libraries with a target must be either all-keyword or all-plain.
Error occurred only on Linux and LLVM 7.0.0
=> [HIPIFY][cmake][fix] Mark all target_link_libraries with PRIVATE keyword

hipify-clang/README.md
Clang 7.0.0 release has a known bug https://bugs.llvm.org/show_bug.cgi?id=36384, thus 7.0.0 is unstable release for Linux and Windows.
Last stable and tested LLVM+Clang release is 6.0.1.
=> [HIPIFY][doc] Readme update

include/hip/hcc_detail/functional_grid_launch.hpp
Let's mark these as deprecated for now, so that users have time to adapt. I've just stumbled across internal examples being written in the present time and still using `hipLaunchParm`, which is outright ghastly, so the only way to get rid of these is to completely remove them in 2.x.
=> hipLaunchKernel, hipLaunchParm are deprecated, and shall be removed.

hipify-clang/src/HipifyAction.cpp
[Issue] https://github.com/ROCm-Developer-Tools/HIP/issues/739
[Resolution] Always use an std::string not a clang::StringRef for replacement
P.S. Occurred only on Linux, on Windows works fine.
=> [HIPIFY][fix][#739] Fix garbage after replacements

include/hip/hcc_detail/code_object_bundle.hpp, src/program_state.cpp
When compiling with Early Finalization enabled in HCC,
the resulting .kernel section of the host object now may
contain more than one device code blobs.  This patch teaches 
the HIP runtime to correctly extract all the
blobs from a .kernel section.
=> Support more than one device code blobs in a single .kernel section

src/hip_memory.cpp
hipMallocArray and hipMalloc3DArray must use sum of bits
of all components.
=> Fix allocation size of arrays with multiple and/or non-32-bit channels

include/hip/hcc_detail/hip_runtime_api.h
=> typedef struct hipFuncAttributes now C compatible.

include/hip/hcc_detail/hip_memory.h, src/hip_memory.cpp
Move the global arrays for hip malloc/free
from a header into a source file such that
there's only an unique copy in an executable
and prevent wasting static memory on the host
=> Move the global arrays for hip malloc/free

src/hip_module.cpp
Issue was causing seg fault while using hipMemcpyDtoD with HIP module APIs.
=> Fixes global symbols tracking in hip_module

include/hip/hcc_detail/hip_memory.h
Need this change to build MIOpen.
=> Define __hip_device_heap in header for hip-clang only

hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, hipify-clang/src/LLVMCompat.cpp, hipify-clang/src/LLVMCompat.h
+ StringRef issue, which is finally moved to LLVM from Clang
+ Renamed getBeginLoc() and getEndLoc() resolution for Expr and TypeLoc classes
+ Support all the previous LLVM versions via LLVCompat
=> [HIPIFY][LLVMCompat] Support of upcoming LLVM 8.0

src/hip_hcc.cpp, src/hip_hcc_internal.h
Output the process ID together with the Thread ID and other information is needed for HIP debugging since HIP applications may be written using multiple processes. For example,  Sugon is currently testing HPL, which has separated HIP process generated on each GPU by MPI.
=> Support of printing process ID for HIP tracing 

bin/hipcc
HIP/VDI is removing x86_64 from its directory structure. During transition hipcc needs to support both directry structure to avoid breaking regression tests. After transition x86_64 will be cleaned up.
=> Let hipcc handle HIP_VDI_HOME without x86_64

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/program_state.hpp, src/program_state.cpp
Temporary reverting the following PRs related to relying on metadata for kernargs until we get a better understanding of its interaction with early finalization and resolve correctness and performance issues it exposes.
https://github.com/ROCm-Developer-Tools/HIP/pull/731
https://github.com/ROCm-Developer-Tools/HIP/pull/772
=> Revert metadata for kerarg

src/hip_hcc.cpp, src/hip_hcc_internal.h, src/hip_memory.cpp
Requires https://github.com/RadeonOpenCompute/hcc/pull/819 
Fallback to 2D memcpy kernel still pending.
=> Added support for pinned 2D SDMA copy

hipify-clang/src/ArgParse.cpp, hipify-clang/src/ArgParse.h, hipify-clang/src/main.cpp
1. Option -temp-dir for temporary directory:
+ if not specified system temp is used;
+ creates the directory if the directory doesn't exist (only one level in a tree);
+ reports an error in case of a wrong directory specified, in case of necessity of creating a tree of subfolders, or in case of a filename specified.
2. Option -save-temps for preserving temporary files:
+ if specified temporary files are not being deleted from system temps and user temps as well.
3. Work with files in terms of calculated absolute paths by collapsing all '.' and '..' patterns, resolving symlinks and expanding '~' expression to the user's home directory:
+ to produce correct include paths;
+ to avoid possible errors on file routines.
=> [HIPIFY][#812] Finishing with temps

hipify-clang/src/ArgParse.cpp, hipify-clang/src/ArgParse.h, hipify-clang/src/main.cpp
Option -o-dir for output directory:
+ if not specified source file(s) directory is used;
+ creates the directory if the directory doesn't exist (only one level in a tree);
+ if -o and -o-dir both are specified the hipified file is placed to "-o-dir" + "-o";
+ reports an error in case of a wrong directory specified, in case of necessity of creating a tree of subfolders, or in case of a filename specified.
=> [HIPIFY] Introduce option -o-dir

include/hip/hcc_detail/math_functions.h, tests/src/deviceLib/hipDoublePrecisionIntrinsics.cpp, tests/src/deviceLib/hipFloatMath.cpp, tests/src/deviceLib/hipSinglePrecisionIntrinsics.cpp
Add back the round-to-nearest-even intrinsics back to HIP math
intrinsics as it caused regression.
When we removed these, we caused a regression in PyTorch.
=> Add *_rn functions back into HIP intrinsics

hipify-clang/src/main.cpp
[Reasons]
+ File is opened further by clang
+ There is a regression with LLVM 5.x, when system error occurs: temporary file couldn't be renamed - permission denied.
=> [HIPIFY] Use sys::fs::createTemporaryFile without file opening

hipify-clang/src/main.cpp, tests/hipify-clang/lit.cfg
+ Due to latest Windows SDK implementation based on c++14 features, '-std+c++14' is a must;
+ Doesn't affect older versions of MSVC 2017, 2015 (the latest supported is MSVC 2015);
+ On linux still '-std=c++11' is a must;
+ Exclude '-std=' from lit config.
=> [HIPIFY][win] Set -std=c++14 if MSVC

hipify-clang/README.md, hipify-clang/src/main.cpp, tests/hipify-clang/lit.cfg
+ No need in setting '-x cuda' for the user anymore;
+ Testing and Readme updated accordingly.
=> [HIPIFY] Starts implicitly setting '-x cuda' by hipify-clang itself

hipify-clang/README.md, tests/hipify-clang/lit.cfg
[Reasons]
+ We don't compile kernel code at least for now as HIP kernel syntax is almost equal CUDA's;
+ clang always includes PTX in its binaries, so e.g. a binary compiled with --cuda-gpu-arch= would be forwards-compatible with e.g. sm_35 GPUs.
=> [HIPIFY] Get rid of setting '--cuda-gpu-arch='

tests/src/runtimeApi/memory/hipMemset3D.cpp
This PR doesn't make any logical or functional change.
=> [dtest] Remove redundant arguments from hipMemset3D test

hipify-clang/CMakeLists.txt
hipify-clang could be built by Visual Studio 14 2015 or higher.
[Reason]
hipify-clang contains c++14 features which are not supported even by the latest VS 2013 and the Platform Toolset "Visual C++ Compiler Nov 2013 CTP".
=> [HIPIFY][cmake][win] check for Visual Studio version

hipify-clang/CMakeLists.txt, hipify-clang/README.md
[Reason]
CUDA 10 is supported by cmake since 3.12.3.
=> [HIPIFY][cmake] Change min supported version of cmake to 3.12.3

tests/src/deviceLib/hipAsynchronousStreams.cpp
The test is currently disabled, until the device implementation is
actually checked in. This only tests the synchronous aspects of the
stream.
=> introduce tests for asynchronous streams

src/hip_hcc_internal.h, src/hip_module.cpp
A hash calculated via FNV-1a algorithm is introduced in ihipModule_t, the
internal of hipModule_t. The hash is used by HIP module APIs such as
- read_agent_global_from_module
to determine whether the agent-scope globals for a module have been iterated.
This commit fixes one issue that applications which load / unload modules
frequently would occasionally fail. After deep investigation of the issue it
turns out the old implementation in read_agent_global_from_module uses
hipModule_t as the key, which is not robust enough, as hipModule_t instances
are allocated dynamically so there are cases that one memory address may be
used by multiple hipModule_t instances. The real solution is to introduce a
uniquely identifiable hash for the code object associated with the HIP module.
And that's the …
=> Introduce hash key to HIP module implementation

hipify-clang/src/main.cpp
+ Always check for existence any file or dir, first of all, because real_path and make_absolute differ: real_path additionally performs access on file/dir.
+ Relative path routines in source files implemented similarly to dirs.
+ Error handling improvements.
=> [HIPIFY][fix][#867] Relative paths routines fixes and improvements

docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Driver_API_functions.cpp, hipify-clang/src/CUDA2HIP_Runtime_API_functions.cpp, tests/hipify-clang/unit_tests/libraries/cuRAND/benchmark_curand_generate.cpp, tests/hipify-clang/unit_tests/libraries/cuRAND/benchmark_curand_kernel.cpp
+ for all CUDA versions starting from 7.0
+ add missing functions
+ sync with HIP
+ update CUDA_Runtime_API_functions_supported_by_HIP.md
+ update affected tests
+ fix typos
+ formatting, annotating
=> [HIPIFY] CUDA Runtime API functions total revise (up to CUDA 10.0)

include/hip/hcc_detail/hip_fp16.h, include/hip/hcc_detail/hip_fp16_math_fwd.h, include/hip/hcc_detail/math_functions.h, include/hip/hcc_detail/math_fwd.h, tests/src/deviceLib/hipTestDotFunctions.cpp, tests/src/deviceLib/hipTestNativeHalf.cpp
Introduce Dot functions which are available in the ROCm device library. Forward those prototypes, and introduce HIP API to expose the usage of the dot functions.
HIP Tests are passing.
=> Add Dot functions as amd_mixed_dot function

samples/2_Cookbook/8_peer2peer/peer2peer.cpp
Ignore hipErrorPeerAccessAlreadyEnabled and continue with the test.
=> Fixed HIP error check in P2P sample test

CMakeLists.txt, bin/hipcc
Add HIP_COMPILER to hipConfig, so that HIP packages built with HIP_COMPILER for HIP-Clang will be known during runtime by hipcc. Also add default locations to check for llvm and device-libs.
=> hipcc defaults to HIP-Clang if built with HIP-Clang

src/hip_peer.cpp
Reverts ROCm-Developer-Tools/HIP#873
@mangupta although this fixed the issue of GPU device losing access to host pinned memory, but this would break actual P2P access. hipDeviceEnablePeerAccess actually adds current device to peer device's watch list.
=> Revert "Fixed issue of GPU device losing access to host pinned memory"

bin/hipcc, include/hip/hcc_detail/hip_vector_types.h
Disable linux specific compilation and linking options for windows.
In hip_vector_types.h, hip-clang needs HIP's own implementation for vector types even
on windows. MSVC specific implementation is for building runtime itself, which is compiled
by MSVC.
=> Fix hipcc and hip_vector_types.h for windows

include/hip/hcc_detail/math_functions.h
The bit field packing does not work on windows, therefore do not use bit field to create nan for double precision on windows.
=> Fix nan() for windows

bin/hipcc
Allow hipcc to accept the code-object-v3 flag, and pass it to clang. Some changes in clang upstream as well.
=> hipcc should consume -mcode-object-v3 flag

include/hip/hip_runtime_api.h
This allows hipMalloc and hipHostMalloc be true C functions from application
perspective at compile time, so decltype(hipMalloc) and decltype(hipHostMalloc)
can be computed.
All HIP applications shall now correctly use C-style cast or reinterpret_cast
when invoking hipMalloc and hipHostMalloc.
=> Remove C++ function templates for hipMalloc and hipHostMalloc

bin/hipcc
This should prevent duplicate code object arguments being passed into clang, which causes strange behaviour in toolchains' llc arguments.
=> Consume the code obj args to prevent duplicates

CMakeLists.txt, src/h2f.cpp
The implementation is copied from HCC runtime.
For hcc it has no effect since apps can find them in either hcc runtime or HIP
runtime.
hip-clang needs it in HIP/HCC runtime so that HIP/HCC and HIP/VDI runtime are
swappable.
=> Add __gnu_h2f_ieee and __gnu_f2h_ieee

samples/1_Utils/hipBusBandwidth/hipBusBandwidth.cpp
Still limited by how big -b (beatsperiterations) can be, though should be good enough for regular use.
=> Fix hipBusBW overflow with setting beats/iterations

bin/hipcc
We need to revert this since it does not work with llc and caused regressions with rocblas. We need to find some other way to control object v3.
=> revert hipcc changes about code object v3

src/hip_memory.cpp
Calculate the allocated size based on the width, height and depth.
=> Fix hipMemset3D test

include/hip/hcc_detail/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime_api.h, src/hip_memory.cpp, tests/src/runtimeApi/memory/hipMemset.cpp, tests/src/test_common.cpp, tests/src/test_common.h
`hipMemsetAsync` and `hipMemset` takes `int` as input so we really should use the copy kernel which copies `int`.
This PR fixes some failed cases in TensorFlow where non-zero values are passed to `hipMemsetAsync`.
Also it seems there is no test case for `hipMemsetAsync`, I'll try amend this PR to provide one.
=> Add HIP memset APIs to cope with non-zero initial values of integer types

docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Driver_API_functions.cpp
cuMemsetD32(Async) -> hipMemsetD32(Async) (was hipMemset(Async))
based on: [#933](https://github.com/ROCm-Developer-Tools/HIP/pull/933)
=> [HIPIFY] Change CUDA Driver's functions' cuMemsetD32(Async) mapping

bin/hipconfig
HIP_PLATFORM detection logic relied on finding a working KFD. If it was
found, the platform was set as hcc else as nvcc.
However this logic is flawed since it is possible for the development
system to only have the user mode bits to build HIP application code.
Hence the better logic is to rely on finding a suitable compiler.
The new logic is as follows:
- look for a working HCC. If found, platform is set as hcc.
- else look for a working NVCC. If found, platform is set as nvcc.
- else the platform defaults to hcc for now.
=> [hipconfig] Update HIP_PLATFORM detection logic

tests/hipify-clang/lit.cfg, tests/hipify-clang/lit.site.cfg.in
1. Set -D__LP64__ in case of 64-bit hipify-clang binary [partial workaround for clang's bug [38811](https://bugs.llvm.org/show_bug.cgi?id=38811)]
```c++
C:/GIT/LLVM/trunk/llvm-64-release-vs2017/dist/lib/clang/9.0.0\include\__clang_cuda_device_functions.h(1609,45): error GEF7559A7: no matching function for call to 'roundf'
__DEVICE__ long lroundf(float __a) { return roundf(__a); }
```
```c++
#if defined(__LP64__)
__DEVICE__ long lround(double __a) { return llround(__a); }
__DEVICE__ long lroundf(float __a) { return llroundf(__a); } // ok: llroundf should be used when 64-bit
#else
__DEVICE__ long lround(double __a) { return round(__a); }
__DEVICE__ long lroundf(float __a) { return roundf(__a); } // error
#endif
```
2. Print more system info while testing in the following form:
``` …
```
=> [HIPIFY][tests] Update lit testing infrastructure

include/hip/nvcc_detail/hip_runtime_api.h
Fix for the first part of issue #880.
=> nvcc_detail/hip_runtime_api.h: add missing hipDeviceSetCacheConfig API

include/hip/hcc_detail/device_functions.h, include/hip/hcc_detail/hip_runtime.h
- `immarg`, immediate argument, is enabled on all AMDGPU intrinsics.
Revise device functions using these intrinsics with immediate
arguments.
=> [Device Function] Support immediate argument.

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/hip_runtime_api.h, src/hip_clang.cpp, src/hip_fatbin.cpp, src/hip_hcc.cpp, src/hip_hcc_internal.h
This is to fix some HIP APIs not initializing HIP.  This causes some of the HIP unit tests to fail when HCC's lazy initialization is enabled.
=> reimplement HIP_INIT as hip_impl::hip_init(), add hip_init() to some of the inlined API

include/hip/hcc_detail/hip_runtime_api.h
For code objects with global symbols of length 0, ROCR runtime would
ignore them even though they exist in the symbol table. Therefore the
result from read_agent_globals() can't be trusted entirely.
As a workaround to tame applications which depend on the existence of
global symbols with length 0, always return hipSuccess here.
This behavior shall be reverted once ROCR runtime has been fixed to
address SWDEV-173477
=> HACK for SWDEV-173477

include/hip/hcc_detail/device_functions.h
- `hcc` has no builtin. Need to invoke LLVM intrinsic directly.
=> SWDEV-184380 Fix hcc compilation

src/hip_memory.cpp
Avoid double mapping of devices to hostMalloc buffer
=> Avoid double mapping of devices to hostMalloc buffer

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/hip_runtime_api.h, include/hip/hcc_detail/program_state.hpp, src/hip_module.cpp
This replaces #985.  Any function in `program_state.hpp` that previously iterated over all agents has been converted to instead take a single hsa_agent_t parameter.  This results in program state becoming explicitly initialized once and only once for the requested agent, without the side effect of loading state for the remaining agents.
This change also resulted in simpler code for `hipLaunchKernelGGLImpl` and `hipFuncGetAttributes`.
=> load program state once per agent

include/hip/hcc_detail/hip_runtime_api.h, src/hip_module.cpp
In HIP PR #929, quite a few HIP public APIs were made as inline functions with
hidden visibility. It was necessary to support applications with shared
libraries with GPU kernels launched via hipLaunchKernelGGL(), after HIP runtime
is initialized.
In empirical tests, the implementation has been proved to be a bit too
excessive, especially for hipModuleGetGlobal(). The function is used by another
type of client applications which relies on the existence of this function
within HIP runtime so global symbols from HSA code objects loaded dynamically
at runtime can be retrieved programmtically.
This commit moves hipModuleGetGlobal() back to src/hip_module.cpp, and makes it
visible and not inline, to fulfill requirements for applications
aforementioned. It does not change the behavior of …
=> Make hipModuleGetGlobal be in HIP runtime so it can be discovered at runtime

src/hip_clang.cpp, src/hip_hcc_internal.h, src/hip_module.cpp
__hipRegisterFunction is called during by .init functions during program initialization.
It calls hipModuleGetFunction to locate kernel symbol in code objects. hipModuleGetFunction
assumes current device when locating kernel symbols. This works for HCC but not for hip-clang,
since hip-clang needs to locate kernel symbols for different devices without switching
between devices.
This patch introduces a new hsa agent parameter to ihipModuleGetFunction, which allows
__hipRegisterFunction to choose the correct hsa agent when locating kernel symbols. By
default it uses this_agent(), therefore this patch has no impact on HCC.
=> hip-clang: fix kernel not found on multi-gpu

src/hip_module.cpp
PR#997 caused memory access fault for HCC due to hipMemcpy to a device in a different root complex when running PyTorch mGPU.
This patch restores behavior for HCC as before PR#997 therefore fixes the regression.
=> Fix regression on multi-gpu due to PR#997

hipify-clang/CMakeLists.txt, hipify-clang/README.md
+ Fix the error in cmake: clang 8.0.0 supports CUDA 10.0, not 10.1; only trunk clang 9.0.0 supports CUDA 10.1.
+ Update Readme:
1. clang's bug 36384 is gone, so latest stable release for Linux is clang 8.0.0, which supports CUDA up to 10.0;
2. update dependencies, testing and building notes.
=> [HIPIFY][cmake][doc] Update CMakeLists and Readme cause CUDA 10.1 and clang 8.0.0 are released

Jenkinsfile
Due to a HCC bug in rocm-head, the test fails to compile. Disabling the test until the issue is resolved.
=> [ci] Disable hipLaunchParm.tst for now

hip-config-clang.cmake.in, hip-config-hcc.cmake.in
Define HIP_COMPILER and HIP_RUNTIME in hip-config.cmake to
facilitate other packages identify hip-clang and HIP/VDI
runtime.
=> Fix hip-config.cmake for hip-clang

include/hip/hcc_detail/hip_runtime_api.h
Update /hcc_detail/hip_runtime_api.h
when i try to use mpicc or gcc to compile a c language code which call some hip runtime api , error occurred as
> /path/to/hcc_detail/hip_runtime_api.h:2268:33: error: unknown type name ‘hipFuncAttributes’; 
> hipFuncGetAttributes(hipFuncAttributes* attr, const void* func);
add ' struct ' for the first parameter of hipFuncGetAttributes will get ride of this problem.
=> add little changes in hip_runtime_api.h to work with c language

src/hip_hcc.cpp, src/hip_hcc_internal.h, src/hip_memory.cpp
This changes the behavior from synchronizing the currently set TLS device.
=> In hipFree, synchronize owner of memory

CMakeLists.txt
This should fix the jenkins build machines.
=> Add COMGR relative path for build machines

include/hip/hcc_detail/hip_ldg.h
- Check its value instead of whether it's defined or not.
=> [hip] Fix use of `__HIP_CLANG_ONLY__` in `hip_ldg.h`.

include/hip/hcc_detail/hip_common.h, include/hip/hcc_detail/hip_fp16.h, include/hip/hcc_detail/hip_runtime.h
- Separate the definition of `__HCC_OR_HIP_CLANG__`, `__HCC_ONLY__`, and
`__HIP_CLANG_ONLY__` into hip_common.h so that it could be included in
hip_fp16.h, which may be included separately in app.
=> [hip] Fix including of hip_fp16.h

hipify-clang/README.md
+ tested with CUDA 9.0, 9,2, 10.0 and 10.1
=> [HIPIFY][doc] Update Readme.md: latest cuDNN 7.5.1.10 is supported

include/hip/hcc_detail/device_functions.h, tests/src/deviceLib/hip_bitinsert.cpp
- It's a common mistake by assuming 1 << shamt would be promoted to
64-bit, if shamt is a 64-bit integer. That's not the case. Replace
that left shift to a 64-bit one to ensure it won't fall into undefined
behavior.
- Fix the host-side implementation as well for device function testing.
=> [Device Function] Fix implementation

include/hip/hcc_detail/device_functions.h
- As the signature of `amdgcn.icmp` is changed for next-gen hip, using
clang builtins is portable way to hide that details.
=> [hip] Re-implement ballot using AMDGCN builtins

bin/hipcc
- With `--rpath`, app's RUNPATH is set to the temporary library path
during build. Instead, `--rpath-link` should be used to leave RUNPATH
untouched. User should set LD_LIBRARY_PATH or system ld.so.conf to
proper setting.
=> [hip] Repace `--rpath` with `--rpath-link`

src/hip_hcc.cpp
This change is to avoid HIP runtime causing TF ihipexception error when there's no access to amdgpu driver.
=> Return hipErrorInsufficientDriver status when CPU device not found

tests/src/deviceLib/hipVectorTypesDevice.cpp
- Current clang disallows any invocation of wrong-side functions even
under context with type-inspection only. Work around that by adding a
variant of `std::decl` with `__device__` attribute.
=> [test] Add device variant of `std::declval`.

hipify-clang/src/ArgParse.cpp, hipify-clang/src/ArgParse.h, hipify-clang/src/main.cpp
+ Only a generation of transformation map of CUDA entities supported by HIP is implemented.
+ 3 hipify-clang options are added: -perl, -o-perl-map, -o-perl-map-dir.
+ OptionsParser's mode is changed from OneOrMore to Optional to support hipify-perl generation without actual hipification.
+ Add explicit control of source files specification absence in case of no perl generation.
=> [HIPIFY][perl] Initial support of hipify-perl generation from hipify-clang

include/hip/hcc_detail/hip_runtime_api.h, src/hip_memory.cpp
Default lock is fine grained and adds an AMD specific hipExtHostRegisterCoarseGrained flag for coarse grained lock.
=> Add fine grained host memory lock support

src/hip_hcc.cpp
Avoid creation of extra queues/resources on invisible devices.
=> Maintain HIP_VISIBLE_DEVICES for kernel launch

hipify-clang/src/CUDA2HIP.cpp, tests/hipify-clang/unit_tests/samples/2_Cookbook/1_hipEvent/hipEvent.cpp, tests/hipify-clang/unit_tests/samples/2_Cookbook/2_Profiler/Profiler.cpp
+ Add missing cuda_profiler_api.h to hip/hip_profile.h transformation.
NOTE: HIP Profiler API is under development. This is NOT WORKING example.
TODO: Find out a way to generate HIP_SCOPED_MARKER, HIP_BEGIN_MARKER, HIP_END_MARKER, declared in hip/hip_profile.h in particular place (signatures are to obtain).
=> [HIPIFY][tests] Add reverse engineered HIP sample Profiler

docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Driver_API_functions.cpp, include/hip/hcc_detail/driver_types.h, include/hip/hcc_detail/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime_api.h, samples/2_Cookbook/11_texture_driver/texture2dDrv.cpp, src/hip_memory.cpp
+ Make hip_Memcpy2D struct compatible with CUDA_MEMCPY2D struct
+ Add hipMemcpyParam2D support in nvcc fallback path
+ Update hipify-clang, tests and docs accordingly
=> [HIP][HIPIFY] Make hipMemcpyParam2D coherent with cuMemcpy2D

include/hip/hcc_detail/device_functions.h
The SZ field should minus by 1 since SIZE range is 1..32. Also add comments that results may vary.
=> Fix bug in __smid not setting correct size

bin/hipcc
We now always need device lib path when compiling and not need it at linking.
=> Fix device lib path for hip-clang.

bin/hipcc
If there is -g, do not add -O3 by default.
If HIP_VDI_HOME is not set, set HIP_VDI_HOME based on hipcc directory for HIP/VDI runtime.
For HIP/VDI runtime, set HIP_CLANG_PATH and DEVICE_LIB_PATH based on HIP_VDI_HOME only if they exist.
This allows using HIP/VDI runtime with hip-clang installed at /opt/rocm/llvm and device lib installed
at /opt/rocm/lib.
=> Fix hipcc for hip-clang.

include/hip/hcc_detail/hip_fp16.h
The original `if defined` guard was there to provide an alternative code path when compiling with g++; however, this breaks when a plan vanilla clang is used for compiling host code.  The new guard fixes the problem.
=> fix compilation error when host compiler is clang

CMakeLists.txt, src/hip_module.cpp, src/program_state.inl
Use the code object manager library to parse the code object metadata. Both
code object v2 and v3 formats are now supported for HCC generated binaries.
=> Add support for code object v3

include/hip/hcc_detail/hip_complex.h
Changed hipFloatComplex and hipDoubleComplex from a struct to a typedef of float2 and double2 respectively. This is to resolve SWDEV-185448 where conversion to type float2 was causing errors. Adjusted hipDoubleComplex as well to keep the format consistent.
=> Structured hipFloatComplex as typedef of float2, and hipDoubleComplex as typedef of double2.

include/hip/hcc_detail/hip_texture_types.h
This is required to support texture type for hip-clang.
=> Add device_builtin_texture_type attribute to texture type for hip-clang

bin/hipcc
There is soft link /opt/rocm/bin/.hipVersion, therefore when hipcc is executed
as /opt/rocm/bin/hipcc, it will set HIP_VDI_HOME to /opt/rocm, which is
incorrect. Check ../lib/bitcode instead to identify HIP_VDI_HOME.
=> Fix default HIP_VDI_HOME

include/hip/hcc_detail/device_functions.h
- Add parenthese to silence repeative compilation warnings across
projects built against hip.
=> [hip] Minor fix to silence compilation warnings.

docs/markdown/hip_kernel_language.md
--target-isa= didn't work any longer.
'''[TARGET GPU] = wasn't visible.  
added gfx900 to list of gpus
=> fixed targets flag and TARGET GPU

bin/hipcc
- Once HIP_VDI_HOME is defined but HIP_CLANG_INCLUDE_PATH is not,
calculate it directly without HIP_CLANG_PATH is defined or not;
Otherwise, we may leave HIP_CLANG_INCLUDE_PATH undefined, if clang is
not installed following the official way (so far, HIP-Clang breaks
that), we may leave HIP_CLANG_INCLUDE_PATH undefined before its uses.
=> [hipcc] Revise include path calculation.

hip_prof_gen.py
Convert python 2 constructs to python 3 compatible ones.
In python 3, print is a function, so use write methods (which are always functions) instead.
In python3 keys() returns an iterator, rather than a list. This means you can't change the data structure that is being iterated over. Converting this iterator into a list mimics the python 2 behavior.
=> Make hip_prof_gen.py compatible with both python 2 and 3

src/program_state.inl
This fixes a bug where GCC++ on Ubuntu 18.04 creates failing executables compared to GCC++ on 16.04 and clang++. While creating function names on Ubuntu 18.04, dl_phdr_info seems to provide a non-zero value for dlpi_addr on initial iteration, and an empty string in dlpi_name. This is causing failure when linking with g++, since the empty string prevents the kernel function from being loaded. Clang++ and GCC on UB16 provide a zero value for dlpi_addr. To fix this, we need to verify both addr and name exists, so that /proc/self/exe can be properly loaded.
=> Fix dlpi_name info empty when using GCC on ub18

src/hip_module.cpp
Gfx8 devices should have 800, not 512, SGPRs per SIMD
=> Fixed bug in hipOccupancyMaxPotentialBlockSize for the SGPRs limitation of gfx8 devices

hip_prof_gen.py
hip_api_name fixed to be inline to suppress 'not used' warning
=> hip_api_name fixed to be inline to suppress not used warning

samples/0_Intro/module_api_global/runKernel.cpp, samples/0_Intro/module_api_global/vcpy_kernel.cpp
module_api_global relies on a HCC only feature which allows host code
to write to device variables. This feature does not exist in CUDA
or hip-clang, which causes the sample not working in CUDA or hip-clang.
This patch fixes the sample by using standard features of CUDA and
hip-clang. The fixed sample works in HCC, CUDA and hip-clang.
=> Fix sample module_api_global for hip-clang

include/hip/nvcc_detail/hip_runtime_api.h
The wrong function was called with the given arguments. cudaOccupancyMaxPotentialBlockSize can only be called with max. 5 arguments. There is an extra function cudaOccupancyMaxPotentialBlockSizeWithFlags which additionally can accept optional flags - like described in the [official documentation].
So currently (without this fix) the following error occurs when compiling a hip program, which uses hipOccupancyMaxPotentialBlockSize, for a nvidia device:
```
/opt/rocm/include/hip/nvcc_detail/hip_runtime_api.h:1217:44: error: no matching function for call to ‘cudaOccupancyMaxPotentialBlockSize(int*&, int*&, const void*&, size_t&, int&, unsigned int&)’
cerror = cudaOccupancyMaxPotentialBlockSize(minGridSize, blockSize, func, dynamicSMemSize, …
```
=> Fix call to cuda library

include/hip/hcc_detail/hip_vector_types.h
Typo introduced here:
commit 67abac1365c26fdf499e288ac7f3eec88b52c816
Author: Alex Voicu <alexandru.voicu@amd.com>
Date:   Mon Jun 24 20:02:09 2019 -0500
Put 3-wide vector types on a ketogenic diet. (#1180)
=> Fix typo ( T in Vec3_cmp = needs to be int ).

hipify-clang/src/ArgParse.cpp, hipify-clang/src/ArgParse.h, hipify-clang/src/main.cpp
+ Add option -print-stats-csv to dump statistics to CSV file
+ If -o-dir is specified, CSV file will be dumped there
+ Generate 1 summary file sum_stat.csv in case of multiple sources
=> [HIPIFY] Statistics to CSV file dumping revise

src/hip_memory.cpp
Previously bounds were not checked before doing a hipMemset, which can result in undefined behavior, since a larger block than allocated memory can be overridden.
A bounds check is implemented which results in error in case bounds are breached.
This should be bring hipMemset and hipMemsetAsync to behave like cuda counterpart respectively.
=> Adding bounds check before hipMemset

include/hip/hcc_detail/hip_vector_types.h
With this change, `hipVectorTypesDevice` passed
=> Fix even more typo.

Jenkinsfile
Reverts ROCm-Developer-Tools/HIP#1010
=> [ci] Renable hipLaunchParm.tst since HCC bug is fixed

docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Driver_API_types.cpp, include/hip/hcc_detail/driver_types.h, include/hip/hcc_detail/hip_runtime_api.h, samples/2_Cookbook/11_texture_driver/texture2dDrv.cpp, src/hip_memory.cpp, src/hip_texture.cpp, tests/hipify-clang/unit_tests/samples/2_Cookbook/11_texture_driver/texture2dDrv.cpp
[Reason] To be compatible with CUDA [#1133]
Update HIP code, hipify-clang, tests and docs
[TODO] Add support of the corresponding functions on nvcc fallback path
P.S. This is a PR based on closed #1135
=> [HIP][HIPIFY] Split HIP_ARRAY_DESCRIPTOR struct to HIP_ARRAY_DESCRIPTOR and HIP_ARRAY3D_DESCRIPTOR

bin/findcode.sh, bin/finduncodep.sh
+ Source files are the first to go. It is needed for in-place hipification in order to avoid errors with included but already hipified header files.
+ More extensions support for batch processing.
=> [HIPIFY][bash] Make 'find' sorted by extension

include/hip/hcc_detail/texture_functions.h
JIRA ISSUE : SWDEV-151668
Issue when reading UChar and UShort textures as Normalized Float
signed/unsigned char,short range is remapped to 0.f->1.f on texture read
=> UChar and UShort textures as Normalized Float

src/hip_module.cpp
Allocate 8 bytes more for the new implicit kernarg - multi grid synchronization. Any consumers of this argument should note that it will be appended to the end of existing implicit kernargs.
=> Increased the number of implicit-kernarg bytes to 56

hipify-clang/src/ArgParse.cpp
+ Fixes the following assert in debug version [#941]:
`Assertion failed: (S.empty() || S[0] != '-') && "Option can't start with '-", file C:\GIT\LLVM\trunk-for-submits\llvm-project\llvm\lib\Support\CommandLine.cpp, line 440`
+ DashDash option left declared in order to be listed in help.
=> [HIPIFY][#941][fix] Workaround for an assert on forbidden option "--"

hipify-clang/src/HipifyAction.cpp
Fixes [ [HIPIFY][Win][debug] Assertion failed: LexLevel == 0 && "cannot use lookahead while lexing"](https://github.com/ROCm-Developer-Tools/HIP/issues/1239)
=> [HIPIFY][#1239] Fix an assert

tests/src/runtimeApi/memory/hipMemcpy.cpp
The hipMemcpy-size uses a maxElem calculated from the total GPU mem /8. Then it will allocate 4 times that amount of host memory. This tests begins failing when there is not enough host memory, such as on systems with 32GB GPU mem, and 16GB RAM. This fixes the test if not enough host memory is available on the system.
=> Fix hipMemcpy-size test running out of Host Mem

docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
CUDA version - version in which API has appeared and (optional) last version before abandoning it; no value in case of earlier versions < 7.5.
=> [HIPIFY][doc] Populate Driver API doc with CUDA version field

docs/markdown/CUBLAS_API_supported_by_HIP.md
CUDA version - version in which API has appeared and (optional) last version before abandoning it; no value in case of earlier versions < 7.5.
=> [HIPIFY][BLAS][doc] Populate cuBlas API doc with CUDA version field

docs/markdown/CUFFT_API_supported_by_HIP.md
CUDA version - version in which API has appeared and (optional) last version before abandoning it; no value in case of earlier versions < 7.5.
=> [HIPIFY][FFT][doc] Populate cuFFT API doc with CUDA version field

docs/markdown/CUSPARSE_API_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_SPARSE_API_functions.cpp
+ CUDA version - version in which API has appeared and (optional) the last version before abandoning it; no value in case of earlier versions < 7.5.
+ Fix typos.
=> [HIPIFY][SPARSE][doc] Populate cuSPARSE API doc with CUDA version field

docs/markdown/CUDNN_API_supported_by_HIP.md
+ CUDA version - version in which API has appeared and (optional) last version before abandoning it; no value in case of earlier versions < 7.5.
+ Fix typos.
=> [HIPIFY][DNN][doc] Populate cuDNN API doc with CUDA version field

src/hip_memory.cpp
To match the behavior with CUDA equivalent API.
=> hipPointerGetAttributes- Change hipErrorUnknown to hipErrorInvalidValue

docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Runtime_API_types.cpp
+ CUDA version - version in which API has appeared and (optional) the last version before abandoning it; no value in case of earlier versions < 7.5.
+ Fix typos, add missing references.
=> [HIP][doc] Populate CUDA Runtime API doc with CUDA version field

src/hip_event.cpp, src/hip_hcc.cpp, src/hip_hcc_internal.h, src/hip_stream.cpp
Do not lock the HIP stream while waiting for an event.  Unlike previous versions of HCC, waiting on an event no longer causes HCC to reclaim stream resources, it only causes HCC to free HSA signals associated with the event.
Remove unused `_kernelCnt` member.
=> remove stream locks where it is safe to do so

src/hip_module.cpp
Fixed missed ihipLogStatus for erroneous returns in hipFuncGetAttributes
=> Fix missing logstatus in hipFuncGetAttributes

hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, tests/hipify-clang/unit_tests/headers/headers_test_10.cu, tests/hipify-clang/unit_tests/headers/headers_test_11.cu
...while including HIP main header file, which is inserted now after #indef controlling macro, or after #pragma once, if it's occurred earlier.
+ Add a couple of unit tests.
ToDo: Check backward compatibility on older clang versions.
=> [HIPIFY][fix][#211] Taking into account include guard controlling macro

bin/hipcc
When HIP-VDI depends on an llvm-amdgpu package, the include clang directory is not properly assessed.
We need this fixed for CI.
=> Fix HIP-VDI using incorrect include files

CMakeLists.txt, include/hip/hcc_detail/channel_descriptor.h, include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/hip_runtime_api.h, include/hip/hcc_detail/program_state.hpp, include/hip/hip_common.h, include/hip/hip_hcc.h, src/functional_grid_launch.inl, src/hip_hcc.cpp
- Change to compile the HIP runtime with hidden visibility by default
- Set visibility to default for public APIs and a few internal APIs
=> Compile HIP runtime with hidden visibility by default

bin/hipify-perl
Add missing hipHostRegister flags to hipify-perl for flags that are defined and supported in hip_runtime_api.h
=> [HIPIFY] Add missing hipHostRegister flags to hipify-perl

tests/src/deviceLib/hipAsynchronousStreams.cpp
"Changed the third arg of the functions __hip_as_write_block and __ockl_as_write_block from ulong to uint64_t so as to fix the compilation error in windows"
=> [dtests] Fixed build issues with hipAsynchronousStreams.cpp on windows

tests/src/kernel/hipLaunchParm.cpp
"Removed unwanted #include sys/time.h , gettimeofday() and timeval variables and this also helps avoid compilation error in windows due to gettimeofday() call equivalent of which is not available in windows"
=> [dtests] Fix build issues with hipLaunchParm.cpp on windows

tests/src/clara/clara.hpp, tests/src/hipEnvVar.cpp, tests/src/hipEnvVarDriver.cpp
Platform specific implementation to use setenv(), popen, pclose system calls for linux and  _putenv_s, _popen, _pclose for windows. platform is detected with predefined macros.
Replaced getopt with clara based implementation which is platform independent.
=> [dtests[ Fix build issues with hipEnvVar*.cpp on windows

tests/src/runtimeApi/memory/hipMemcpy_simple.cpp
Compilation error being observed on windows due to aligned_alloc() call. Mapped the call to _aligned_malloc() for windows.
=> [dtests] Fix build issue with hipMemcpy_simple.cpp on windows

tests/src/runtimeApi/memory/hipMemoryAllocateCoherentDriver.cpp
Compilation error being observed due to popen(), pclose() and setenv() linux calls on windows. Replaced with appropriate calls on windows.
=> [dtests] Fix build issues with hipMemoryAllocateCoherentDriver.cpp on windows

include/hip/hcc_detail/math_functions.h
MSVC assert.h has no guard for include once. The macro assert overrides
device assert definition. Do not include it for device compilation.
=> Fix assert for windows.

include/hip/hcc_detail/hip_fp16.h
this fixes the rocprim benchmark build with hip-clang
=> [hip] Allow from/to half conversion on host side.

include/hip/hcc_detail/hip_runtime.h
Add back decl for hipHccModuleLaunchKernel and hipExtModuleLaunchKernel for HIP/VDI only
=> Fix missing decl for hip-clang

include/hip/nvcc_detail/hip_runtime_api.h
Fix for github #1183 issue reported
=> Compilation failure on nvcc path when using hipChannelFormatKind

hipify-clang/src/main.cpp
This fixes a hanging of unit tests.
=> [HIPIFY][fix] Set the correct exit value for hipify-clang if errors

samples/1_Utils/hipInfo/hipInfo.cpp
If we don't call hipSetDevice(i), the total/free memory will be wrong.
=> Set device before processing each one

hipify-clang/CMakeLists.txt
[Reason] LLVM became c++14 last week due to the following change:
37508d3dd94b0154861a90b1909d17b01400df99
Replace llvm::integer_sequence and friends with the C++14 standard version
=> [HIPIFY][cmake] Explicitly set c++14

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime.h, include/hip/nvcc_detail/hip_runtime_api.h, src/hip_module.cpp, tests/src/gcc/LaunchKernel.c, tests/src/gcc/LaunchKernel.h, tests/src/gcc/gpu.cpp
Reclaiming the old deprecated hipLaunchKernel symbol to implement hipLaunchKernel that matches cudaLaunchKernel signature.
Note: Incorporated all review comments
=> [HIP] Reclaiming hipLaunchKernel API

bin/hipcc
Currently hipcc uses -O3 for hip-clang by default but uses -O0 if -g is used. This
causes surprise for users since -g should not affect default opt level.
=> Do not change opt level for -g for hip-clang

hipify-clang/src/ArgParse.cpp, hipify-clang/src/ArgParse.h, hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, hipify-clang/src/LLVMCompat.cpp, hipify-clang/src/LLVMCompat.h, hipify-clang/src/main.cpp, tests/hipify-clang/lit.cfg, tests/hipify-clang/lit.site.cfg.in, tests/hipify-clang/unit_tests/libraries/cuComplex/cuComplex_Julia.cu, tests/hipify-clang/unit_tests/libraries/cuSPARSE/cuSPARSE_03.cu, tests/hipify-clang/unit_tests/pp/pp_if_else_conditionals.cu, tests/hipify-clang/unit_tests/pp/pp_if_else_conditionals_01.cu, tests/hipify-clang/unit_tests/pp/pp_if_else_conditionals_01_LLVM_10.cu, tests/hipify-clang/unit_tests/pp/pp_if_else_conditionals_LLVM_10.cu
+ Start to translate preprocessor's false conditional blocks too:
based on clang's https://reviews.llvm.org/D66597;
available only starting from LLVM 10.0 or trunk.
+ Option `-skip-excluded-preprocessor-conditional-blocks` for skipping excluded conditional blocks:
the default behaviour for hipify-clang built with LLVM < 10.0;
false by default for hipify-clang built with LLVM 10 or trunk.
+ Add 4 preprocessor unit tests, 2 of which are LLVM 10.0 only.
+ Update couple of existing tests by setting `-skip-excluded-preprocessor-conditional-blocks` option:
update lit testing accordingly.
=> [HIPIFY][#207][fix] Translate all preprocessor's conditional blocks

docs/markdown/hip_porting_guide.md
The table in the hip_porting_guide showing math library equivalents between CUDA and HIP is broken. This is a key feature for converting to AMD hardware. This fix corrects the broken link and moves the library equivalents to sit under the "Porting a New Cuda Project" header.
=> Fix Broken Link in hip_porting_guide

src/hip_memory.cpp
Reverts ROCm-Developer-Tools/HIP#1346
This implementation requires review and possible rework.
=> Revert "Using HSA API for hipMemsetAsync"

include/hip/hcc_detail/device_functions.h
This is a critical change for milestone 1 performance issue.
=> [hip] Stop using `noduplicate` and replace it with `convergent`.

CMakeLists.txt
The reason to introduce this is that RENAME fails on SLES and CentOS systems.
=> Replacment of RENAME command in CMakeLists.txt

bin/hipify-perl, hipify-clang/src/HipifyAction.cpp, tests/hipify-clang/unit_tests/libraries/cuRAND/benchmark_curand_kernel.cpp, tests/hipify-clang/unit_tests/samples/axpy.cu, tests/hipify-clang/unit_tests/samples/square.cu
+ Enclose template instantiation kernel calls into round brackets, leave regular kernel names unchanged (hipify-perl doesn't handle cases with macros).
+ Fix corresponding tests.
PS. hipify-perl couldn't handle correctly the following cases due to macros expansion disability, thus hipify-clang should be used instead:
#define KERNEL_NAME_MACRO axpy<float>
#define KERNEL_CALL_MACRO axpy<float><<<1, 2>>>
#define KERNEL_ARG_LIST_MACRO a, x, y
// CUDA:
KERNEL_NAME_MACRO<<<1, 2>>>(KERNEL_ARG_LIST_MACRO);
KERNEL_CALL_MACRO(KERNEL_ARG_LIST_MACRO);
// hipify-perl:
hipLaunchKernelGGL(KERNEL_NAME_MACRO, dim3(1), dim3(2), 0, 0, KERNEL_ARG_LIST_MACRO);
KERNEL_CALL_MACRO(KERNEL_ARG_LIST_MACRO);
// hipify-clang:
hipLaunchKernelGGL((KERNEL_NAME_MACRO), dim3(1), dim3(2), 0, 0, KERNEL_ARG_LIST_MACRO); …
=> [HIPIFY][#1400] Fix Template Instantiation kernel launch (clang & perl)

src/hip_memory.cpp
This fixes #1412 , #1403 and #1234.
This is temporary fix and has side effects - hipFree will also free pointers which needed hipHostFree calls for freeing.
=> [HACK] Temporary fix in hipFree for hipManagedMalloc use

src/hip_memory.cpp
Added Null check in hipMemcpyDtoD(), hipMemcpyHtoD(), hipMemcpyDtoH(), hipMemcpyHtoH() to avoid seg fault when src or dest is passed as NULL.
=> SWDEV-202043 hipMemcpyDtoD() issue

bin/hipify-perl, hipify-clang/src/CUDA2HIP_Perl.cpp, tests/hipify-clang/unit_tests/device/math_functions.cu
+ Do not treat somenamespace::device_function_name as a device function
+ Fix generation of warnUnsupportedDeviceFunctions function in hipify-clang
+ Update hipify-perl based on hipify-clang -perl generation
+ Update device test math_functions.cu for hipify-perl
[Restrictions]
- hipify-perl is yet unable to handle function declarations in user namespaces
- hipify-perl is yet unable to handle using directive
=> [HIPIFY][perl][fix] Treat ::device_function as a device function

bin/hipify-perl, docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Runtime_API_functions.cpp
+ Update hipify-perl and CUDA_Runtime_API_functions_supported_by_HIP.md accordingly
=> [HIPIFY][#1437] Fix: cudaFuncGetAttributes to hipFuncGetAttributes is supported

hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, tests/hipify-clang/unit_tests/device/device_symbols.cu, tests/hipify-clang/unit_tests/libraries/cuRAND/benchmark_curand_kernel.cpp, tests/hipify-clang/unit_tests/libraries/cuRAND/poisson_api_example.cu
cudaMemcpyToSymbol, cudaMemcpyToSymbolAsync, cudaGetSymbolSize, cudaGetSymbolAddress, cudaMemcpyFromSymbol, cudaMemcpyFromSymbolAsync
+ Add a corresponding cudaSymbolFuncCall matcher.
+ Add device_symbols.cu test for the above 6 functions, update existed.
+ Fix dim3() type cast issue, update affected tests.
TODO: Do the same in hipify-perl
=> [HIPIFY][#1435] Add HIP_SYMBOL wrapper to the templated Device Symbol argument of the following functions

hipify-clang/README.md
+ LLVM 9.0.0 is latest stable release, no patches are needed
+ The latest CUDA 10.1 Update 2 is supported
+ Tested on Windows and Linux
=> [HIPIFY][doc] Update README.md due to LLVM 9.0.0 release

bin/hipify-perl, hipify-clang/src/CUDA2HIP_Perl.cpp, hipify-clang/src/CUDA2HIP_Scripting.h, hipify-clang/src/HipifyAction.cpp
cudaMemcpyToSymbol, cudaMemcpyToSymbolAsync, cudaGetSymbolSize, cudaGetSymbolAddress, cudaMemcpyFromSymbol, cudaMemcpyFromSymbolAsync
+ Perl part of [#1441]
+ Implement function generateSymbolFunctions() in hipify-clang for that purposes
+ Update hipify-perl
TODO: Eliminate dim3() issue in hipify-perl as well
=> [HIPIFY][#1435][perl] Add HIP_SYMBOL wrapper to the templated Device Symbol argument of the following functions:

hipify-clang/README.md
Due to LLVM 9.0.0 release, which still needs X86 for NVPTX, LLVM trunk - doesn't.
=> [HIPIFY][doc] Return X86 target back in LLVM's cmake

hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, tests/hipify-clang/unit_tests/samples/reinterpret_cast.cu
+ Affected functions: hipFuncSetCacheConfig, hipFuncGetAttributes
+ Add a corresponding Matcher cudaReinterpretCastArgFuncCall
+ Add reinterpret_cast.cu test
TODO: Do the same for hipify-perl
=> [HIPIFY][#1439] Add reinterpret_cast to args of some functions

include/hip/hcc_detail/device_functions.h
=> Map clock64() to __builtin_readcyclecounter()

include/hip/hcc_detail/device_functions.h, src/hip_hcc.cpp, src/hip_hcc_internal.h, src/hip_memory.cpp
Addresses SWDEV-136570. hipMemGetInfo changed to compute free memory based on information from kfd instead of relying on hc::am_tracker.
=> Reimplement hipMemGetInfo

bin/hipify-perl, hipify-clang/src/CUDA2HIP_Perl.cpp, hipify-clang/src/HipifyAction.cpp, tests/hipify-clang/unit_tests/device/atomics.cu, tests/hipify-clang/unit_tests/libraries/cuRAND/benchmark_curand_kernel.cpp, tests/hipify-clang/unit_tests/samples/axpy.cu, tests/hipify-clang/unit_tests/samples/square.cu
[REASON]
1. hip-clang is fine with the templated kernel launch, brackets are unneeded: HIP_KERNEL_NAME(...) __VA_ARGS__
2. HCC is not, thus: HIP_KERNEL_NAME(...) (__VA_ARGS__)
[TODO] Clean-up entirely kernel name wrapping when HCC is finally obsolete.
+ Update perl generation, hipify-perl, and affected tests accordingly.
=> [HIPIFY] Return to wrapping with HIP_KERNEL_NAME(...) macro of a template instantiation kernel launch

hipify-clang/src/ArgParse.cpp, hipify-clang/src/ArgParse.h, hipify-clang/src/CUDA2HIP_Perl.cpp
+ Get rid of --o-perl-map option for Perl output filename: the output name now is always hipify-perl
+ Option --o-perl-map-dir renamed to --o-hipify-perl-dir
Cmd example for generating hipify-perl script to the particular directory:
hipify-clang -perl --o-hipify-perl-dir=../../bin
=> [HIPIFY][perl] Start to generate hipify-perl under an option -perl

src/hip_module.cpp
This fixes a bug where the Kernel_descriptor is constructed with the wrong kernel name if the code object is v3
=> fix kernel descriptor bug with code object v3

include/hip/hcc_detail/hip_complex.h, include/hip/nvcc_detail/hip_complex.h
hip_complex.h has real() and imag() which was conflicting with std:real and std:imag hence build failure observed in HPC app.
=> [HIP]Fixed redefinition of real() & imag() [SWDEV#201461]

include/hip/nvcc_detail/hip_runtime_api.h
This fixes the usage of an uninitialized `cdattr` variable in `hipDeviceGetAttribute` for the CUDA backend when taking the switch default, as detailed in #1317.
Note that the `directed_tests/runtimeApi/device/hipGetDeviceAttribute.tst` test fails for me, but it already did before applying this patch. Let's see what CI says!
=> Fix usage of uninitialized variable in hipDeviceGetAttribute

include/hip/hcc_detail/hip_runtime_api.h, include/hip/hcc_detail/library_types.h, include/hip/hip_runtime.h, include/hip/library_types.h, include/hip/nvcc_detail/hip_runtime_api.h
[Reason]
Currently, hipFFT, hipBLAS and other HIP libs use their own data types, prefixed with HIPFFT or HIPBLAS, whereas in CUDA those types are common and declared in library_types.h
[TODO]
Switch hipFFT, hipBLAS and other HIP libs to use common library_types.h.
=> [HIP] Introduce library_types.h as a common header for libs

tests/src/runtimeApi/memory/hipArray.cpp, tests/src/runtimeApi/module/hipLaunchCooperativeKernel.cpp
SWDEV-203971:
directed_tests/runtimeApi/module/hipLaunchCooperativeKernel.tst - Disabling test temporarily until driver support is available.
directed_tests/runtimeApi/memory/hipArray.tst
=> Fix for directed tests failure

bin/hipify-perl, hipify-clang/README.md, hipify-clang/src/CUDA2HIP.cpp, hipify-clang/src/CUDA2HIP.h, hipify-clang/src/HipifyAction.cpp, hipify-clang/src/HipifyAction.h, hipify-clang/src/Statistics.cpp, hipify-clang/src/Statistics.h, tests/hipify-clang/lit.cfg, tests/hipify-clang/lit.site.cfg.in, tests/hipify-clang/unit_tests/libraries/CUB/cub_01.cu
+ Respond to the feature request in #1460
+ Add one matcher (will be more)
+ Update Maps and Statistics
+ Add cub_01.cu unit test
+ Update lit harness to support standalone CUB
+ Update hipify-perl (only CUB header is supported for now)
**[IMPORTANT]**
clang (and hipify-clang) works correctly only with official NVLabs version on GitHub.
Compilation of CUB from official CUDA release has conflicts with THRUST.
Thus, to compile CUB sources, option "-I" should be specified to the cloned CUB from NVLAB on [GitHub](https://github.com/NVlabs/cub).
=> [HIPIFY][CUB] Initial support (hipify-clang only)

tests/hipify-clang/lit.cfg
+ affects cuDNN and CUB tests, paths to libraries of which are defined by CUDA_DNN_ROOT_DIR and CUDA_CUB_ROOT_DIR
+ Warn about excluding and why, for instance:
"WARN: cuDNN tests are excluded due to unset CUDA_DNN_ROOT_DIR"
=> [HIPIFY][tests] Exclude tests for the libs, which are not defined in cmake command line

hip_prof_gen.py
This change is necessary for HPCToolkit to use Roctracer to produce code centric profiling view.
=> Fix struct declaration for C

CMakeLists.txt
Adding Code Object Manager file to rtc to resolve address of Bundled_code_object in libhiprtc.so
=> Adding code object manager to rtc

samples/2_Cookbook/11_texture_driver/texture2dDrv.cpp
Fixes SWDEV-203394.
Currently in runTest() returns true, even if the texture reference copy does not happen. Using the existing testResult Flag to return from runTest().
=> Use the correct return type in runTest in 11_texture_driver sample.

hipify-clang/CMakeLists.txt
+ Fix: set destination for all installing files to ${CMAKE_INSTALL_PREFIX}
=> [HIPIFY][cmake] Add install rule for clang-resource-headers

bin/hipcc
Reverts ROCm-Developer-Tools/HIP#1298
Reverting to avoid critical issues seen for ROCm2.10.
=> Revert "hipcc defaults to code object v3"

hipify-clang/CMakeLists.txt, hipify-clang/README.md
I've tested HIPIFY in the HIP-Clang CI environment on Ubuntu 16.04 and successfully builds and installs hipify-clang with ROCm LLVM+Clang.
```
root@498447af48dc:/root/HIP/hipify-clang/build# cmake -DCMAKE_INSTALL_PREFIX=../dist -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/root/llvm-project/build/dist ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting …
```
=> [HIPIFY][cmake] Make CMakeLists use default 3.5.1 for Ubuntu 16.04

tests/hipify-clang/lit.cfg, tests/hipify-clang/unit_tests/device/atomics.cu
[Reason] To support maximum CUDA features in offline tests
+ Add CUDA_VERSION >= 800 restriction for atomics.cu
[TODO] Find a way to use or exclude atomicAdd for doubles if LLVM < 7, because
LLVM 6.0.1 and older do not use --cuda-gpu-arch in clang's Driver code at all (option is only declared)
=> [HIPIFY][tests] Set max clang's CudaArch for corresponding CUDA version

bin/hipify-perl, hipify-clang/src/CUDA2HIP_Runtime_API_types.cpp, tests/hipify-clang/unit_tests/samples/vec_add.cu
`hipWarpSize` has been renamed to warpSize in `struct hipDeviceProp_t ` a long ago, thus eliminate it in hipify-clang.
=> [HIPIFY][#1569] Fix

hipify-clang/src/main.cpp, tests/hipify-clang/unit_tests/libraries/CUB/cub_03.cu
By implicit unconditional passing -fno-delayed-template-parsing option (which appeared in LLVM 3.8.0, thus doesn't need compatibility wrapping) to hipify-clang.
[Reason] To parse uncalled template functions otherwise they are not parsed without calling, thus not hipified.
Affects cub_03.cu test, which has uncalled global template function.
=> [HIPIFY] Disable delayed template parsing

tests/src/runtimeApi/memory/hipMemcpy_simple.cpp, tests/src/test_common.h
_aligned_malloc() on Windows first takes size, then alignment, which is the opposite of how the similar function behaves on Linux. Memory allocated by it also has to be freed using _aligned_free(), unlike Linux where we can use regular free().
Edit aligned_alloc() macro and add a aligned_free() one to align with the above behaviour.
=> Fixes for hipMemcpy_simple on Windows

src/hip_hcc_internal.h, src/hip_memory.cpp, src/hip_module.cpp
background: for the cooperative groups feature, runtime needs to setup a new implicit argument for multi-grid synchronisation as follows;
- set to 1 if the kernel is launched with hipLaunchCooperativeKernel
- set to a pointer to a properly initialized struct mg_info if the kernel is launched with hipLaunchCooperativeKernelMultiDevice
=> [hip] add support for implicit kernel argument for multi-grid sync

include/hip/hcc_detail/hip_vector_types.h
The improvement is based on the ideas here: https://t0rakka.silvrback.com/simd-scalar-accessor. It yields significantly better ISA when the base's .xyzw members are used.
=> Improve scalar access into vector types.

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/hip_runtime_api.h, samples/2_Cookbook/13_occupancy/occupancy.cpp, src/hip_module.cpp, tests/src/runtimeApi/module/hipLaunchCooperativeKernel.cpp, tests/src/runtimeApi/module/hipOccupancyMaxActiveBlocksPerMultiprocessor.cpp, tests/src/runtimeApi/module/hipOccupancyMaxPotentialBlockSize.cpp
Raising this PR after closing PR#1484. This contains the same changes as in PR#1484 and also fixes according to the review comments. Thanks.
Matched the interface for cooperative groups with Cuda. This includes the templates for hipOccupancyMaxActiveBlocksPerMultiprocessor, hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags and hipOccupancyMaxPotentialBlockSize.
Also, modified the tests related to these API's according to the changes made.
=> Cooperative groups match with cuda SWDEV-205006

include/hip/hcc_detail/hip_atomic.h
For certain atomic ops which lack hardware support we use CAS loops as the implementation. At the moment these loops are TAS, which makes them even more awful than they need to be. This takes the trivial step of using TTAS, which is notably cheaper for us since the first T boils down to a trivial read.
=> Make CAS loops use the TTAS idiom.

tests/src/runtimeApi/memory/hipMemset2D.cpp
Reverts changes made in #1399. This is a RT api test. For testing hipMemAllocPitch , a new test should be written and that should use correct memset API.
=> [dtest] Fix hipMemset2D test

include/hip/hcc_detail/hip_atomic.h
This fixes a deadlock introduced by the switch to TTAS loops, and is therefore mildly urgent (to prevent the CI from hoovering in the broken code).
=> Fix deadlock, remove old __sync_* use.

INSTALL.md
HIP-clang is already used below instead of AMD-clang
=> [HIP][doc] Fix typo: AMD-clang -> HIP-clang

hipify-clang/src/LLVMCompat.cpp, hipify-clang/src/LLVMCompat.h, hipify-clang/src/main.cpp
[Reason] clang starting from 9.0.0 can compile Host and Device code in a single job.
LLVM < 9 continues using `--cuda-host-only`.
=> [HIPIFY] Introduce --cuda-compile-host-device for LLVM >= 9

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/hip_runtime_api.h, samples/2_Cookbook/13_occupancy/occupancy.cpp, src/hip_module.cpp, tests/src/runtimeApi/module/hipLaunchCooperativeKernel.cpp, tests/src/runtimeApi/module/hipOccupancyMaxActiveBlocksPerMultiprocessor.cpp, tests/src/runtimeApi/module/hipOccupancyMaxPotentialBlockSize.cpp
Reverts ROCm-Developer-Tools/HIP#1560.
Reverting this for HIP-Clang/ VDI builds for 2.10.
=> Revert "Cooperative groups match with cuda SWDEV-205006"

include/hip/hcc_detail/hip_runtime_api.h
- Add missing function templates of them in hip-clang. So far, that function template is only available on HCC path.
=> [HIP] Correct headers and add missing function templates for hip-clang.

CMakeLists.txt
[REASON]
Those vars (may) used by cmake in subdirectories (#1571)
=> [HIP][cmake] Move all *_INSTALL_DIR variables up before first add_subdirectory()

hipify-clang/src/HipifyAction.cpp, tests/hipify-clang/unit_tests/kernel_launch/kernel_launch_01.cu
+ Add a corresponding test kernel_launch_01.cu
+ Add isBefore() check to avoid crash on Replacement with negative length
TODO:
+ Compatibility with former LLVM versions
+ More complicated kernel launch tests
=> [HIPIFY][#1409] Fix for kernel launch macro expansion

src/hip_event.cpp, src/hip_hcc.cpp, src/hip_hcc_internal.h
The following lines were causing the race condition when two threads update the same event:
https://github.com/ROCm-Developer-Tools/HIP/blob/815a601dcba213d5040dab8be7ac824b573cedd2/src/hip_event.cpp#L135-L142
Thread A creates marker 1. 
Thread B creates marker 2 after marker 1. 
Thread B stores marker 2 in Event. 
Thread A stores marker 1 in Event.
The deadlock mentioned in the comment was not observed.  Previously, hipEventQuery would lock the hipStream because of resource cleanup inside the HCC runtime, but this is no longer the case.  I do not believe the deadlock condition in the comment is currently reproducible.
=> fix race condition in hipEventRecord

include/hip/hcc_detail/hip_fp16.h
The __half2 comparison intrinsics had surprising behaviour which did not match CUDA, this corrects the oversight.
=> __half2 should walk like CUDA and talk like CUDA

include/hip/hcc_detail/macro_based_grid_launch.hpp, include/hip/hip_ext.h, include/hip/hip_hcc.h, samples/0_Intro/module_api/launchKernelHcc.cpp, samples/0_Intro/module_api_global/runKernel.cpp, samples/2_Cookbook/11_texture_driver/texture2dDrv.cpp, src/hip_hcc.cpp, src/hip_module.cpp, tests/src/hipHcc.cpp, tests/src/runtimeApi/module/hipModuleGetGlobal.cpp, tests/src/runtimeApi/module/hipModuleTexture2dDrv.cpp
With these changes #1338 shouldn't be needed.
=> Rename hip/hip_hcc.h to hip/hip_ext.h

hipify-clang/src/main.cpp
[Reason] Leave overriding opportunity for -D, -std=c++XX, etc.
=> [HIPIFY] Reorder options propagation to clang

include/hip/hcc_detail/hip_runtime.h
- The revised `hip/hip_ext.h` have that declarations.
=> Remove redundant declarations.

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/hip_runtime_api.h, include/hip/hip_ext.h, tests/src/kernel/hipExtLaunchKernelGGL.cpp, tests/src/runtimeApi/module/hipModuleGetGlobal.cpp
This depends on https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/183. It supersedes https://github.com/ROCm-Developer-Tools/HIP/pull/1523.
=> Add support for extended launch syntax.

tests/src/hipEnvVarDriver.cpp, tests/src/test_common.cpp, tests/src/test_common.h
hipEnvVarDriver would not run with windows because of the following:
1. Windows didn't recognize unsetenv(). Windows use _putenv.
2. Path to hipEnvVar used forward slashes (/) while windows only recognizes back slashes (\)
3. _popen on windows does not actually return NULL on invalid command, therefore after checking for directed_test/hipEnvVar, it doesn't go to check hipEnvVar at the same level.
Changes have been made to fix these.
=> Updated hipEnvVarDriver to work with Windows

include/hip/hcc_detail/hip_complex.h
The sign in the y component returned from hipConj incorrect for double-complex.  Fix to match as in hipConjf above
=> fix complex conjugate for double-complex

include/hip/hip_ext.h
few critical apps and mathlibs cannot be built without this fix.
=> Fix mathlib and app builds with hip-clang.

src/hip_hcc.cpp
This follows the convention established elsewhere for checking `_av.get_is_empty()` before creating a marker.
- https://github.com/ROCm-Developer-Tools/HIP/blob/ebe0c56f4f700863a85984ccfbaf4c4d53e2805c/src/hip_hcc.cpp#L1059
- https://github.com/ROCm-Developer-Tools/HIP/blob/ebe0c56f4f700863a85984ccfbaf4c4d53e2805c/src/hip_hcc.cpp#L1550
=> hipStreamSynchronize can skip marker if stream is empty

include/hip/hcc_detail/helpers.hpp, tests/src/cppstd/hipInvocable11.cpp, tests/src/cppstd/hipInvocable11Fallback.cpp, tests/src/cppstd/hipInvocable14.cpp, tests/src/cppstd/hipInvocable17.cpp, tests/src/cppstd/is_callable_test.hpp
This will fix issue #1621. It also adds tests for `is_callable` with c++11, c++14, and c++17.
The fallback implementation was completely broken so I rewrote it so it pass the tests as well. This should be used instead of PR #1631.
I ran the tests manually to see if it passes, but I didn't run them in hip test suite because I couldn't get it to work so please let me know if I need to change something so the test can work better.
=>  Fix helper header when using c++17 

include/hip/hcc_detail/device_functions.h, include/hip/hcc_detail/device_library_decls.h, src/hip_stream.cpp
Handled the HCC version check appropriately as few of the directed tests (SWDEV-212161) were failing when hcc was bumped to 3.0.
=> fixed directed tests fail when hcc bumped to 3.0

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/hip_runtime_api.h, src/hip_module.cpp
[Background] it was found that if lazy linking used for a library that calls  hipExtLaunchMultiKernelMultiDevice API then this API can get the wrong program_state object for looking up device kernels leading to a "No device code available" error in this API.
To fix this issue, the API was refactored to be inline and get and pass the correct program_state to an internal hip API to request a multi-device kernel launch.
=> [hip] refactoring hipExtLaunchMultiKernelMultiDevice API

include/hip/hcc_detail/hip_runtime_api.h
- Use the correct condition for HIP VDI runtime.
=> Fix `hipExtLaunchMultiKernelMultiDevice` refactoring.

include/hip/hcc_detail/hip_vector_types.h
Fix linker issues where incompatible definitions of the vector types are used in gcc and clang.
Now there is a single consistent data type, which either uses the clang `ext_vector_type` extension, or the equivalent gcc `vector_size`.
Eliminate specialization for size 3 data types and round up to nearest power of two. Likely some code could be saved by automatically computing the next power of two instead of manually specifying it as a template argument.
There still are some issues with these data types and C++ projects which assume that the members of, e.g., `double4` are strictly `double`. Implicit type conversion does not work in all situations. This is the case e.g. for serialization libraries (cereal) applied to the HIP vector types, or python bindings (pybind11). The HIP data types …
=> fix linking of vector types with gcc

include/hip/hcc_detail/hip_runtime_api.h
rocBLAS still compile part of code using HCC. With the headers shipped with HIP-Clang, __HIP_VDI__ is turned on unconditionally, that cause a conflict linkage definition for `hipExtLaunchMultiKernelMultiDevice` between the one defined here and the other one defined in `include/hip/hcc_detail/functional_grid_launch.hpp`
=> Only add `hipExtLaunchMultiKernelMultiDevice` for non-HCC compilers.

bin/hipify-perl, docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Driver_API_functions.cpp, hipify-clang/src/CUDA2HIP_Driver_API_types.cpp, hipify-clang/src/CUDA2HIP_Runtime_API_functions.cpp, hipify-clang/src/CUDA2HIP_Runtime_API_types.cpp
+ hipMemAllocHost is deprecated, use hipHostMalloc instead
+ hipMemAllocManaged -> hipMallocManaged
+ hipFreeHost -> hipHostFree
+ cudaMemset3D(Async) -> hipMemset3D(Async)
+ update docs and hipify-perl accordingly
=> [HIPIFY] Revise HIP runtime

hipify-clang/src/CUDA2HIP_Runtime_API_types.cpp, include/hip/hip_runtime_api.h
Step 1. Set the same values for RT error codes as for analogous Driver's
[Reason] RT's and Driver's error codes unification in CUDA 10.2
=> [HIP] Unify hipError_t (Step 1)

include/hip/hcc_detail/hip_vector_types.h
- That's a high overhead part, which needs enabling ONLY if necessary.
So far, rocFFT cannot be built due to that overhead. Previous 1m compilation time is increased up to 6+ minutes. For other sources, that overheads are too large to be measurable.
=> [hip] Add macro guarding the enum conversion for scalar accessor.

Jenkinsfile, bin/hipconfig
- Bump version HIP version to 3.1
- Switch HIP tests to run on top of ROCm 3.0
=> bump version to 3.1

tests/src/runtimeApi/memory/hipMemcpy.cpp
Windows has a complicated way of calculating how much system memory is available for the gpu (see https://docs.microsoft.com/en-us/windows-hardware/drivers/display/calculating-graphics-memory). At most half of system memory is available for the gpu for allocation, however not all of it can be resident on the device at the same time. To calculate that amount it would require a lot of DDI calls to query the aperture sizes and commit limits. That's unreasonable to do in a test, so instead just cap the amount of system memory we report to 40%.
=> Fix OOM issues with hipMemcpy test on Windows

include/hip/hcc_detail/texture_functions.h
SWDEV-213602
Fixed compilation warning: array designators are a C99 extension [-Wc99-designator]
=> replace array designator C99

include/hip/hcc_detail/hip_runtime.h
This is to allow force enable cuda wrapper for OpenMP for flexibility
=> Add macro __HIP_ENABLE_CUDA_WRAPPER_FOR_OPENMP__

hipify-clang/README.md
+ Tested on Windows and Linux: no changes are needed
=> [HIPIFY][doc] LLVM 9.0.1 is the latest stable release now

src/hip_memory.cpp
SWDEV-151670: Issue with 3D texture with 4 components
SWDEV-151671: Issue with 2D layered texture with 4 components
Fixed memcpy when memory is allocated with driver API's.
Github issues: #1755 
Fixed 3D default case when array type is not set during memory allocation.
=> Fix texture 3D & 2D layered with N components

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/hip_runtime_api.h, src/hip_module.cpp
This PR is a follow-up on PR# https://github.com/ROCm-Developer-Tools/HIP/pull/1698 and it makes two more APIs (hipLaunchCooperativeKernel/hipLaunchCooperativeKernelMultiDevice) inline so that they can work correctly with lazy binding.
=> [hip] refactoring cooperative kernel launch APIs

bin/hipify-perl, docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, hipify-clang/src/CUDA2HIP_Driver_API_types.cpp, hipify-clang/src/CUDA2HIP_Runtime_API_types.cpp, include/hip/hcc_detail/hip_runtime_api.h, include/hip/hip_runtime_api.h, include/hip/nvcc_detail/hip_runtime_api.h, samples/0_Intro/bit_extract/bit_extract.cpp, samples/0_Intro/square/square.hipref.cpp, src/hip_event.cpp, src/hip_hcc.cpp, src/hip_memory.cpp, src/hip_stream.cpp, tests/hipify-clang/unit_tests/samples/square.cu, tests/src/dynamicLoading/complex_loading_behavior.cpp, tests/src/runtimeApi/event/record_event.cpp, tests/src/runtimeApi/module/hipExtLaunchMultiKernelMultiDevice.cpp, tests/src/runtimeApi/stream/hipStreamAddCallback.cpp, tests/src/runtimeApi/stream/hipStreamSync2.cpp
Step 2. Make a few hipError codes deprecated
Update hipify-clang, hipify-perl, docs and samples accordingly
=> [HIP] Unify hipError_t (Step 2)

src/hip_memory.cpp
hipMemcpyToSymbol and hipMemcpyFromSymbol are corrected to handle the error scenario.
#1735 should succeed with this.
=> hipMemcpysymbol fixes

src/hip_hcc.cpp, src/hip_hcc_internal.h, src/hip_module.cpp
Detect when an explicit printf buffer flush is required in a device/stream synchronization function.
=> Detect when an explicit printf buffer flush is required

include/hip/hcc_detail/channel_descriptor.h, include/hip/hcc_detail/device_functions.h, include/hip/hcc_detail/driver_types.h, include/hip/hcc_detail/hip_complex.h, include/hip/hcc_detail/hip_fp16.h, include/hip/hcc_detail/hip_fp16_gcc.h, include/hip/hcc_detail/hip_runtime.h, include/hip/hcc_detail/hip_vector_types.h, include/hip/hcc_detail/texture_functions.h, include/hip/hip_runtime_api.h, src/hip_hcc_internal.h
Fixes SWDEV-218626 and SWDEV-218629
Changes:
- Revert "`static inline` in a header, just like excess sugar in a diet, causes bloat (#1692)"
This reverts commit be70b9f7e711e1ae72fcfebb2fa0fdcbebbcf5fc.
- Revert "Fix rocFFT build failure (#1777)"
This reverts commit 753277422a0637ff2bf541c7b43dfaaa2b12c9f6.
=> Revert PRs that break ROCm builds

tests/src/deviceLib/hip_bitextract.cpp
The randomly generated offset+width may exceeds 32, which causes
a left shift operation with 32-offset-width. As an unsigned number
that is greater than 32 and causes undefined behavior. When the
test is compiled without -mavx it is still OK. However when
the test is compiled with -mavx, the undefined behavior causes
wrong results and test failure.
This patch adjusts width so that offset+width<=32 always.
=> Fix test hip_bitextract.cpp

CMakeLists.txt, src/hiprtc.cpp
Removing dependency on filesystem, so libstdc++fs is no longer required to link
=> Remove filesystem dependency in hipRTC

CMakeLists.txt
Don't allow `HIP_PATH` to be propagated to `hipconfig`, when run by CMake to detect the package version, as it leads to the wrong version is detected: when there's already HIP of some different version installed in the system and `HIP_PATH` points to its location, `hipconfig` tends to return the version of the installed HIP, rather than the value defined for the distribution. The compiled results report wrong version and spoils the rest of the stack in this case.
First found during the testing of the ebuild for HIP at https://github.com/justxi/rocm/pull/120 and fixed there with clearing `HIP_PATH` just before calling `cmake` as the first measure. But it looks, that the proper fix is like in this request.
=> Clear `HIP_PATH` before version detection

src/program_state.cpp, src/program_state.inl, tests/src/kernel/hipPrintfKernel.cpp
The current implementation skips this procedure for a given device
object when a global symbol is found in the cache.  This is incorrect:
- There could be other undefined globals that have not been previously
encountered further down the list
- If a symbol is found in the cache, it doesn't need to be pinned again
but it still need to be defined for the current executable
Added special case for the printf buffer symbol (already pinned by HCC)
The bug was exposed by running printf on different GPUs.
=> Fix associate code object symbols with host allocation bug

include/hip/hcc_detail/hip_cooperative_groups_helper.h
* There was a bug while computing this_grid().thread_rank(), fixed it.
* The semantics of this_grid().thread_rank() computation is as follows.
1.  Compute number of work-groups to be passed before arriving at current work-group
2.  Using above, compute total number of threads being passed till current work-group
3.  Computer local thread-rank (of current thread) within current work-group
4.  Return sum of above 2 and 3.
=> SWDEV-220503:  this_grid().thread_rank() gives incorrect result

include/hip/hcc_detail/driver_types.h
Currently HIP_TRSF_READ_AS_INTEGER is 0, which makes it impossible via hipTexRefSetFlags() to suppresses the default behavior of having the texture promote integer data to floating point data in the range [0, 1].
Updating these flags to match their Cuda equivalents fixes a lot of potential UB.
=> Update the HIP_TRSF_* flags to match their Cuda equivalents.

src/program_state.inl
Errors from these API calls should be checked and it would help to debug some of the "missing kernel/metadata" errors.
=> add error checking for code object loading

tests/src/texture/hipTexObjPitch.cpp
As per CUDA docs pResViewDesc can only be specified if the type of resource is a CUDA array or a CUDA mipmapped array.
=> [dtest] Avoid resViewDesc for non-array resource in texture creation 

hipify-clang/src/HipifyAction.cpp, hipify-clang/src/LLVMCompat.cpp, hipify-clang/src/main.cpp
+ Add an explicit cast when assigning StringRef to std::string
=> [HIPIFY] Fix build failure against ToT trunk LLVM 11.0.0

hipify-clang/CMakeLists.txt
+ hipify-clang unit tests are passed against CUDA 10.2
=> [HIPIFY][cmake] CUDA 10.2 support starting from LLVM 10.0

tests/src/runtimeApi/module/hipLaunchCoopMultiKernel.cpp
used reinterpret_cast<uint32_t*> for numBlocks, as expected by hipOccupancyMaxActiveBlocksPerMultiprocessor() api.
=> Update hipLaunchCoopMultiKernel.cpp at the line 159

bin/hipcc
- The known target checking should skip `gfx000` as well as it won't be
used in real compilation command formation. The avoid generating
annoying warning on `gfx000`.
=> [hipcc] Skip warning on `gfx000`.

bin/hipcc
- As the builtin headers from clang are installed in the standard
destination, there's no need to add them as system header paths.
There's no need to add HIP headers as system headers as well.
=> [hip] Revise compiler wrapper for HIP-Clang.

include/hip/hcc_detail/functional_grid_launch.hpp, include/hip/hcc_detail/hip_runtime_api.h, samples/2_Cookbook/13_occupancy/occupancy.cpp, src/hip_module.cpp, tests/src/runtimeApi/module/hipLaunchCooperativeKernel.cpp, tests/src/runtimeApi/module/hipOccupancyMaxActiveBlocksPerMultiprocessor.cpp, tests/src/runtimeApi/module/hipOccupancyMaxPotentialBlockSize.cpp
Reverting this for now till we figure out how to avoid the build
breakage.
This reverts commit fa98798b63be461240da98c0c719bf6a92fa44d0.
=> Revert "Match Occupancy APIs syntax with CUDA (#1625)"

src/hip_device.cpp
The break is missing for hipDeviceAttributeMaxTexture3DDepth.
=> missing break statement in hipDeviceGetAttribute

hipify-clang/README.md
Built and tested on Ubuntu and Windows
=> [HIPIFY][doc] Update README.md: LLVM 10.0.0-rc2 - the latest supported LLVM Release

bin/hipcc
Some PyTorch unit tests have regression.  Disabling cov3 to allow more
time to debug and unblock PyTorch
=> Disabling HCC code object v3 generation by default.

include/hip/hcc_detail/device_functions.h, tests/src/kernel/hipShflTests.cpp
Implement additional data-types for shuffles (`long` and `long long`).
Based upon the `double` implementation.
=> Implement long / long long shuffles

Jenkinsfile, src/program_state.inl, tests/src/runtimeApi/module/hipModuleLoadDataMultThreaded.cpp
Even though there is a lock for pushing back to the vector, the references and iterators to the element are used without a lock. This is a problem as other threads will push back to the vector which can invalidate the references and iterators from other threads.
Instead of locking the entire function, I switched to `std::deque` which has stable iterators and references when using `emplace_back`.
=> Use deque instead of vector for code readers so that the iterators and references will be stable

tests/src/runtimeApi/module/hipModuleLoadDataMultThreaded.cpp
Limit the max threads that are launched to 16.
=> [dtests] Fix random timeout failures in hipModuleLoadDataMultThreaded

include/hip/hcc_detail/driver_types.h, src/hip_memory.cpp, tests/src/runtimeApi/memory/hipMemcpy3D.cpp, tests/src/texture/simpleTexture2DLayered.cpp, tests/src/texture/simpleTexture3D.cpp
Fixes #1790 and #1791. hipMemcpy3D still requires further refactoring for different input and output combinations.
=> Fix hipMemcpy3D

bin/hipcc
This is a quick workaround to match HCC behavior for performance since inlining usually
results in more optimization opportunities therefore better performance.
We will fine tuning inline threashold later.
=> Let HIP-Clang inline all functions by default

tests/src/hipEnvVarDriver.cpp, tests/src/test_common.cpp, tests/src/test_common.h
There were several error messages that appeared even if the hipEnvVarDriver.exe test passes and executes successfully. Now it is cleaned up. The following are those instances:
- When popen searches for directed_test directory but does not find it, it outputs an error, then finds the hipEnvVar at the same level. Currently the fix will prompt the test to only output an error if both searches for hipEnvVar fails.
- When assertion is used towards the later half of the test, conditions were set to specifically hide the devices, resulting in No Hip Device detected in the latter half of the test. The fix will make these errors not appear as they are intended to not find any devices. Assertions themselves are untouched.
HipEnvVarDriver.cpp has also been refactored. Reading HipEnvVar will now …
=> Cleaned up error messages for HipEnvVarDriver test

CMakeLists.txt
[Reason] Upcoming hipify-clang's splitting out into a new repository https://github.com/ROCm-Developer-Tools/HIPIFY.
=> [HIP][cmake] Remove dependency from hipify-clang

hipify-clang/README.md
+ Add -DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON for LLVM 10.0.0 or newer
+ Supported versions update
=> [HIPIFY][doc] Update README.md: LLVM 10.0.0-rc3 is supported

bin/hipcc, include/hip/hcc_detail/device_functions.h, include/hip/hcc_detail/hip_runtime.h
There are now two implementations of printf in HIP:
1. The implemenation for HCC is controlled by the HC_FEATURE_PRINTF
macro, and it works only with the HCC compiler used in combination
with the HCC runtime.
2. The implementation for hip-clang requires the VDI runtime, and is
always enabled with that combination.
=> separate printf declaration for vdi/clang

include/hip/hcc_detail/device_functions.h
copy/paste error, need __shfl_xor w/ lane_mask
=> Fix incorrect shfl_xor for Windows

src/hip_memory.cpp
Check size/count of bytes for zero count and return hipSuccess immediately. Used ihipLogStatus for return wherever allowed.
=> return hipSuccess when count is zero

src/hip_hcc.cpp, src/hip_module.cpp
This PR refactors cooperative APIs to use the dedicated cooperative accelerated view introduced in PR#1406 (https://github.com/RadeonOpenCompute/hcc/pull/1406) in HCC.
In addition to the above change, the current PR addresses the following issues found during internal testing:
- added support for hipLaunchCooperativeKernel() to be able to use the NULL/default stream
- added support to return hipErrorCooperativeLaunchTooLarge if requested workload cannot fit on the GPU
- added support to properly return error where two (or more) of the GPUs are the same device (and same stream) in hipLaunchCooperativeKernelMultiDevice() API
- Fixed an issue where a floating point exception occurs if we pass "0" into blockDim in multi-GPU cooperative launch
- Fixed an issue where a multi-GPU launch …
=> [HIP] Refactor cooperative APIs

include/hip/hcc_detail/hip_vector_types.h
- Need to check the availability of `__has_attribute` builtin macro
instead of compiler versions. That's more reliable and portable among
various compilers.
- Provides a very basic support of vectors for unknown compilers.
=> [hip] Improve the portability of the header for vector type support.

bin/hipcc
Currently there is a clang bug on Windows causing duplicate -mllvm options in clang -cc1.
Tempoarily disable -mllvm options for HIP-Clang on Windows until the bug is fixed.
Change-Id: I3a4393ba7745989398dc6c6001722837dad18704
=> Let hipcc not pass -mllvm option to HIP-Clang on Windows

src/hip_module.cpp
Fix two errors in hipOccupancyMaxActiveBlocksPerMultiprocessor.
1) Fix a possible segfault if the user passed in a null pointer for the numBlocks value. Return hipErrorInvalidValue when this situation occurs instead of just blowing up the runtime.
2) Handle the situation when the user is asking for a block size that is larger than what the target device can hold within a single block. Return numBlocks as zero, indicating that no blocks of this size can fit on the device, akin to how we will return 0 if you ask for more LDS space than the device has.
=> Fix errors in occupancy calculation function

samples/1_Utils/hipInfo/hipInfo.cpp, src/hip_hcc.cpp
The maxSharedMemoryPerMultiProcessor attribute is meant to describe
the number of bytes of shared memory (LDS space in AMD terminology)
in each SM (CU in AMD terminology). For instance, on AMD GPUs this
is often 64KB per CU, and some Nvidia GPUs it's 96KB per SM.
This shared memory is a different address space from the normal
global memory. However, the current HIP-HCC properties fill this
in with a size that matches the totalGlboalMem property. This gives
a drastically too-high calculation for the amount of LDS space that
each CU has -- tens of GBs vs. 10s of KBs.
This patch fixes this by pulling the maxSharedMemoryPerMultiProcessor
property from the HSA pool that describes how much workgroup-local
space is available on each CU. The HSA runtime eventually pulls
this from the topology …
=> Fix maxSharedMemoryPerMultiProcessor attribute

bin/hipcc
Fixes SWDEV-226025,
Right now -x c++ can come before libhip_hcc.so which forces the compiler to treat libhip_hcc.so as a text file and generates a lot of gibberish unicode. This PR changes the order of flags ensuring that -x c++ and similar flags come after libhip_hcc.so
Hopefully, this will not have any negative side effect.
=> Don't force compiler to treat libhip_hcc.so as a text file

src/hip_hcc.cpp
Query ROCr to see if we have the proper lower-level support for
cooperative groups -- GWS support through the firmware, driver,
thunk, and ROCr. ROCr does these checks for us, and presents a
query that allows us to see if GWS entries are available for use.
If so, then we have all the lower-level technologies needed, and
we should enable cooperative groups support for HIP.
=> Fix detection of support for cooperative groups

bin/hipcc
Fixes SWDEV-207362,
The output file name should not contribute to picking up the right flags for the compiler. This fix solves issues when the output has conflicting extensions which confuses hipcc to treat them as the source files and add the required flags for them. 
PS: Output file refers to the file followed by -o 
Example: hipcc test.o -o test.hip will add the flags for .hip compilation ignoring the fact that it is an output file
=> Output file name should not change flags picked for compiler

include/hip/nvcc_detail/hip_runtime_api.h
NVCC warned if you tried to use hipOccupancyMaxActiveBlocksPerMultiprocessor
because when passing in a device function pointer, "const void* func" was
insufficient to describe it accurately. Adding a C++ templated class type
definition for this function.
=> Fix occupancy calculations API on NVCC

include/hip/nvcc_detail/hip_runtime_api.h
GCC emits a warning about using static functions like
hipCUDAErrorTohipError inside this function, because it has an
inline directive, but it's not static. Adding static to this function
to silence warnings (and prevent potential problems in the future).
=> Fix compiler warning on NVCC path

include/hip/hcc_detail/device_functions.h, include/hip/hcc_detail/hip_runtime.h
This allows printf to work with hip-clang and HCC runtime. See comments under #1919 for a reported bug and feature request.
=> enable HCC printf when using hip-clang

src/hip_clang.cpp
In __hipRegisterFunction, we should use size argument method instead of initialization list method to initialize std::vector<hipFunction_t> functions.
=> fix a bug when initializing a vector of hipFunction_t

bin/hipcc, include/hip/hcc_detail/hip_runtime.h
HIP-Clang cuda_wrapper headers require clang include path before standard C++ include path.
However libc++ include path requires to be before clang include path.
To workaround this, we pass -isystem /opt/rocm/llvm/lib/clang/11.0.0 instead of
-isystem /opt/rocm/llvm/lib/clang/11.0.0/include to clang, and use
`#include <include/cuda_wrappers/algorithm>` instead.
=> Workaround for libc++ include path for HIP-Clang

cmake/FindHIP.cmake
`FindHIP.cmake` seems to have a debug message in it which is quite ugly when configuring and it ships with upstream deploys. It seems to have been inserted for debugging purposes because the exact same information is pretty printed at the end of the script if not silenced through canonical means.
=> Remove debug message from FindHIP.cmake

include/hip/hcc_detail/functional_grid_launch.hpp, src/hip_module.cpp
Previously, the cooperative launch APIs did not properly log their
errors in the global hipGetLastError variable before returning back
to the user. As such, the APIs would leave hipSuccess in the
last error, which would break some use cases.
This fixes that problem by making a trampoline function that does
the HIP_INIT_API and ihipLogStatus.
=> Fix cooperative launch APIs to set hipGetLastError

bin/hipcc
By default hipcc passes -mllvm options to let HIP-Clang inline all device functions.
--hipcc-func-supp enables function support and disables inline all.
--hipcc-no-func-supp disable function support and enables inline all.
This is a temporary solution to match HCC behavior for performance.
This option is mainly for debugging purpose.
Change-Id: I0c44ac1812bb3cea5c3e5b6e14ebaa45919236f6
=> Add option --hipcc-func-supp for function support

src/hip_memory.cpp, tests/src/runtimeApi/memory/hipMemcpyNegetiveTests.cpp
Fix for segfault seen if invalid kind is passed to hipMemcpy.
=> Fix segfault seen in hipMemcpy [SWDEV-224941]

src/program_state.inl
These symbols are not referenced in the final code but may be left
behind when compiling without optimization.  If this happens, just
ignore them.
=> Ignore undef symbols from the static constexpr members in Coordinates

src/hip_module.cpp
there is a build error when building HIP with latest HCC from GitHub after [PR#1935](https://github.com/ROCm-Developer-Tools/HIP/pull/1935) merged into HIP master branch. this PR changed  blockDimX to blockDim and two lines missed this change where added in the current PR.
=> [hip] fix a build error when building hip with latest hcc

src/hip_texture.cpp, tests/src/texture/hipTex1DFetchCheckModes.cpp
github issue: #1754
Changed as per Nvidia spec:
ResourceDesc::resType is hipResourceTypeLinear ignores address mode and filter mode.
And, if textureDesc::normalizedCoords is set to zero, AddressModeWrap and AddressModeMirror won't be supported and will be switched to AddressModeClamp.
=> tex1Dfetch behaviour for different address mode and filter mode

include/hip/hcc_detail/math_functions.h
libc++ defines fma as template function for auto promotion of mixed-type
arguments. libc++ does not handle _Float16 as _Float16 is not a supported
type by C++ standard. As such, it is unlikely we can commit our fix for
_Float16 to libc++ trunk.
Therefore we handle _Float16 with a template specialization of
__numeric_type in HIP headers.
Change-Id: If01960a657ebf1a7a67463cdcf66fab7458dff3c
=> Fix ambiguity of fma for _Float16 for libc++

src/hip_module.cpp
The old formula adds header size which makes the total size of elf to be greater by 64.
Removing the header size to fix the formula.
=> Removing header size from formula

include/hip/hcc_detail/program_state.hpp, src/hip_clang.cpp, src/program_state.cpp, src/program_state.inl
If the code object is embedded in an already mapped file, and the
lifetime of the mapped file exceeds the lifetime of the executable,
we do not need to make a copy of the binary.
This allows the ROCR to present the code object URI as
file:///path/to/file#offset=X&size=Y.
=> Don't duplicate embedded code objects

src/hip_memory.cpp
hc ampointerinfo is keeping track the size of pointer instead of the size of the data.
=> fix hipIpcOpenMemHandle

bin/hipify-perl, docs/markdown/CUSPARSE_API_supported_by_HIP.md
Based on:
https://github.com/ROCm-Developer-Tools/HIPIFY/pull/95
https://github.com/ROCm-Developer-Tools/HIPIFY/pull/96
SPARSE: added csrgeam, csrgeam2, bsrmv, and csr2csr_compress
Update `hipify-perl` and `CUSPARSE_API_supported_by_HIP.md` accordingly
=> [HIP][SPARSE] sync with HIPIFY's #95 and #96

include/hip/hcc_detail/hip_runtime_api.h, src/hip_event.cpp, src/hip_hcc.cpp, src/hip_hcc_internal.h, src/hip_stream.cpp, src/trace_helper.h, tests/src/runtimeApi/event/hipEventIpc.cpp
Replaces #1984 .
Instead of using HSA IPC signals, this implementation only relies on variables of std::atomic<int> type inside a shared memory region.
The attached test only really makes sure hipEvent IPC calls for a single process are providing correct return values.
A better test is attached, adapted from CUDA samples.
[simpleIPC.zip](https://github.com/ROCm-Developer-Tools/HIP/files/4424278/simpleIPC.zip)
=> add IPC event support

include/hip/hcc_detail/device_functions.h
printf is not currently implemented on hip-clang on Windows and it's causing soft-hang so needs to be disabled for now.
=> disable printf on hip-clang on Windows

hip-config.cmake.in
This is needed to avoid errors about requiring NVCC or HCC defines when including hip_runtime_api.h.
Since hip_runtime_api.h can be included from a host compiler(ie gcc or vanilla clang), `__HIP__` may not be defined so `__HIP_PLATFORM_HCC__` will not be defined resulting in a compile error.
=> Add __HIP_PLATFORM_HCC__ to hip::host target

bin/extractkernel
More recent llvm-objdump has changed disassemble and mcpu arguments to require double dashes.
=> extractkernel obj dump args to use double dashes

include/hip/hcc_detail/math_functions.h, tests/src/deviceLib/hipMathFunctions.cpp
It was for HCC only. HIP-Clang also needs it for __fp16 since AMDMIGraphX uses it.
Change-Id: Id49322b7b89ef799accdf6b47627a6fce51d1ab5
=> Enable template max and min for HIP-Clang

bin/hipcc
This is to match nvcc behavior, speed up compilation of C++ programs, and fix some
compilation issue where C++ programs are compiled as HIP programs.
Currently it is controlled by an environment variable
HIP_COMPILE_CXX_AS_HIP. By default it is 1, where
hipcc treats .cpp files as HIP programs. If it is
set to 0, hipcc will treat .cpp files as C++ programs.
This is because some math libraries are still not
ready for the change, however rocBLAS and rocFFT
require this feature for OpenMP, therefore put it
under an environment variable so that rocBLAS
and rocFFT can use it.
Change-Id: I56a51e27079df850ee39d4217fb647c22d79f612
=> Let hipcc treats .cpp files as C++ files for HIP-Clang

include/hip/nvcc_detail/hip_runtime_api.h
Several values for the `flags` argument to `hipSetDeviceFlags` were defined in `include/hip/hcc_detail`, but not in `include/hip/nvcc_detail`.  This change adds the possible arguments to the function in `nvcc_detail/hip_runtime_api.h`.
=> Define missing flags for hipSetDeviceFlags on nvcc

bin/hipcc, bin/hipconfig
Add support for hipconfig to display details on HIP-Clang compiler and update HIP_COMPILER and HIP_RUNTIME to include clang and rocclr. Also, add hipcc flags --cxxflags and --ldflags to support HCC users who used hccconfig flags.
=> Update hipconfig to support HIP-Clang

include/hip/hcc_detail/hip_runtime_api.h
Change-Id: I75ed28a5862daffc0778910d7ba3b97f51a87949
=> [HIP-Clang] Fix typos in hipBindTextureToMipmappedArray

include/hip/hcc_detail/hip_runtime_api.h
prevent macro redefinition by adding "HIP_"
=> Refactor DEPRECATED macro to HIP_DEPRECATED

include/hip/hcc_detail/hip_runtime.h
Make declarations consistent with [devicelibs' ockl.h](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/amd-stg-open/ockl/inc/ockl.h)
Without the attribute these functions don't have "readnone" LLVM IR attribute. And so some optimizations fails, e.g. Loop Invariant Code Motion doesn't hoist these calls out of a loop.
=> Add __attribute__((const)) to grid related functions declarations

bin/hipify-perl, docs/markdown/CUBLAS_API_supported_by_HIP.md
Add support for vector and matrix async functions
Adding gemm_ex batched functions
Update hipify-perl and CUBLAS_API_supported_by_HIP.md accordingly
=> [HIPIFY][HIP][doc] Sync with HIPIFY's #150 and #152

docs/markdown/CUBLAS_API_supported_by_HIP.md, docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md, docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md, docs/markdown/CUDNN_API_supported_by_HIP.md, docs/markdown/CUFFT_API_supported_by_HIP.md, docs/markdown/CURAND_API_supported_by_HIP.md, docs/markdown/CUSPARSE_API_supported_by_HIP.md, docs/markdown/cuComplex_API_supported_by_HIP.md
+ All the docs are generated by `hipify-clang --md`
These docs are being called directly from the official ROCm documentation: https://rocmdocs.amd.com/en/latest/Programming_Guides/Programming-Guides.html
=> [HIPIFY][HIP][doc] Update all CUDA2HIP docs: replace with auto-generated
